### ISSUE TITLE
geninfo incompatible with LLVM gcov 7.0

### ISSUE THREAD

**Issue by sakra** [linux-test-project/lcov#10]
The code in geninfo to determine the version of the gcov tool no longer works for LLVM gcov 7.0. It results in the following error:

    geninfo: Use of uninitialized value $version_string in substitution (s///) at /usr/local/bin/geninfo line 1914.
    geninfo: Use of uninitialized value $version_string in pattern match (m//) at /usr/local/bin/geninfo line 1917.
    geninfo: Use of uninitialized value $version_string in pattern match (m//) at /usr/local/bin/geninfo line 1930.
    geninfo: Use of uninitialized value $gcov_version_string in pattern match (m//) at /usr/local/bin/geninfo line 3720.
    geninfo: Use of uninitialized value $gcov_version_string in pattern match (m//) at /usr/local/bin/geninfo line 3720.

The output of `gcov --version` under OS X:

     $ gcov --version
     Apple LLVM 7.0.0 (clang-700.0.72)

**Comment by oberpar** [comment]
Thanks for reporting. This issue should be fixed with commit 1ad4f7779b7721e311e552209e110e08bbf18fa1.

**Comment by vandong** [comment]
today, i have just run with current version and get this issue again
