### ISSUE TITLE
How to find which are the functions not covered in test coverage.

### ISSUE THREAD

**Issue by Nitika123** [linux-test-project/lcov#100]
I am writing unit test coverage for react. I got the following report for a file:

```
% Stmts : 100      
% Branch : 100      
% Funcs : 91.3       
% Lines : 100 
Uncovered Line #s : NIL
```
I could see from the lcov coverage that report generated that the number of functions covered are 21/23. Is there any way to find which are the 2 functions left?

**Comment by henry2cox** [comment]
Hi -
Sorry for the long delayed reply.  In view of the age of this issue, I'm going to close this issue after replying.
I'm trying to clean up the issue list if I can.
Please reopen if you need to - and also list your requirements and/or suggest a set of features that would resolve the issue to your satisfaction.  I guarantee you that any feature that you would find interesting/useful is also interesting and useful to some other users - and so is worth considering and possibly worth implementing.

The easiest way to see what isn't covered is to generate an HTML report ('genhtml -o report my_data.info ...') and then view it ('google-chrome ./report/index.html;)
Look at the top-level table to see which directories contain un-covered lines/functions/branches - then click on the link to go to one of them.  Look at that table to see which files have unexercised coverpoints - and click on one of them.
There is a link at the top of the source code view which will take you to the function detail table - which will show you what is and is not covered, and will enable you to navigate to source code.

You might also want to look at the "--filter function" option to genhtml (TOT - not in the release module yet) - which collapses identical functions and does some alias analysis.  You might also want to look at the "--demangle-cpp" option;  there are cases where gcc/llvm will generate multiple copies of some inline functions and then not call all of them.
Those functions have slightly different mangled names - and demangling enables lcov to merge them the way you likely want to see.

Hope that helped - and sorry for the long delay.

Henry
