### ISSUE TITLE
genhtml: macOS c++filt does not support --no-strip-underscoreS

### ISSUE THREAD

**Issue by janosvitok** [linux-test-project/lcov#102]
After upgrade to macOS 11 and Xcode 12.2, genhml stopped working.

Currently, c++filt Apple LLVM 12.0.0 (clang-1200.0.32.27) supports only --no-strip-underscore (not -underscoreS)

Commit 04a3c0ed1b4b9750b2ac5060aac0e6d5a3b9da7f that introduced this parameter is inconsistent in what it says in commit message and in code. I can't tell what really changed in c++filt nor when.

I can only  tell that it worked before the upgrade (macOS 10.15.7,  Xcode 12.1).

It seems that in recent llvm c++filt the switch is on by default for macOS: https://github.com/llvm/llvm-project/commit/e84468c1f145e9a5e54640ebdc78bc40c7da3fce#diff-68923a586c64daf44cf810ad253b1c9edae04e0e6e61db170fc1b2368f1dc388R74

**Comment by henry2cox** [comment]
I didn’t see any other responses yet.   Not sure if this will help you:

-       To work around the issue – or to check what the options to c++filt need to be for that platform – you  can use the ‘genhtml_demangle_cpp_params’ option to override the “--no-strip-underscores” option that genhtml wants to pass by default – and set the parameter list to something else.

-       genhtml_demangle_cpp_params can be set using either “—rc=…” or the lcov config file.

I don’t have access to your platform/OS – so I can’t check if it works or not.

Henry

**Comment by janosvitok** [comment]
Yes, that's what I'm using now. Sorry, I should have written that, at least for other users.
