### ISSUE TITLE
Lcov not counting if statement but code inside if is counted

### ISSUE THREAD

**Issue by ccarvajalz** [linux-test-project/lcov#104]
There is an issue when executing tests where if statement is not counted but code inside it is counted.
For example:
     351           0 :     if (port) {
     352      179865 :         forced = port->is_forced_down;
     353             :     }

**Comment by lkersting** [comment]
possibly related to #115

**Comment by henry2cox** [comment]
do you have a testcase which illustrates the issue?
If so:  what platform and version (linux RHEL8, windows 10, etc), what toolchain and version (gcc/10, LLVM/13, ...)?  What is your compile command?
Do you see the same result with current lcov TOT?

Also note that lcov is merely presenting the data extracted by gcc/gcov.  Please take a look at the gcov output to see if gcov is claiming the same thing:  if so - this is a gcc/gcov issue.  If not, then this is an lcov bug.
Superficially, this looks similar to #185 .

Thanks
Henry

**Comment by henry2cox** [comment]
No response in 2 years.
Closing issue.
If this is still a problem:  please reopen or file a new issue.  Provide testcase.
