### ISSUE TITLE
What is needed on a function to be counted in function coverage?

### ISSUE THREAD

**Issue by ccarvajalz** [linux-test-project/lcov#105]
I have 2 different cases I need to confirm:
1. I have a portion of a function which is excercised and counted and the other one shouldn't be counted as it is not excercised by the test. Is this function supposed to be counted in function coverage percentage as a hit?

Example of the code:

      29           2 : get_string(char *var) {
      30           2 :     char *p;
      31             : 
      32           0 :     if (NULL != (p = (strchr(var, '/')))) {
      33           0 :         *p = '\0';
      34             :     }
      35           0 : }

2. I have a function which is not counted as hit in function coverage but it has all the lines hit in line coverage. Why can this be happening?

Example of code:
     362         658 : set_event(void) {
     363         658 :     int flags         = FLAG_ID
     364         658 :     int initial_value = 0;
     365             : 
     366         658 :     event_id = event(initial_value, flags);
     367         658 :     return;
     368             : }

**Comment by henry2cox** [comment]
For the second case (the source lines of your function are exercised but the function coverage metric says “not hit”):

-          Check your lcov report to see if the compiler generated 2 (or more) variants of the same function.  You can see an example of this in lcov issue #98 – along with the solution/workaround/hack that I use.

For the first case:  I’d check that your build matches your code (i.e., that the version of the .gcda/.gcno files match the source file version).  You ought not to be able to hit a function without exercising any code within it.

Which versions of compiler and tools are you using?

Henry

**Comment by ccarvajalz** [comment]
Hello,

I have verified there is no duplication on the report, the onyl thing I see different from other functions is that final } has no count. 

Gcc version is 9.3
gcov version is 9.3
lcov version 1.15

**Comment by henry2cox** [comment]
Do you have a testcase that you can share?
(I think you reported two slightly different issues – a testcase for each of them would be useful).

Thanks

Henry

**Comment by henry2cox** [comment]
Seems that this issue is open and unchanged/uncommented for more than 2 years.
Is this still a problem (with latest code from TOT)?
If so - can you update what your testcase looks like and what results you see.
If problem is resolved, can you close the issue?
If no update in a few weeks, I will assume there is no interest and/or issue resolved - and will go ahead and close it.
Thanks

**Comment by henry2cox** [comment]
> If no update in a few weeks, I will assume there is no interest and/or issue resolved - and will go ahead and close it.

5 months later/no updates.  Closing the issue.

If there is still a problem:  please either reopen this issue or file a new one.  Please include a detailed description of the problem, and ideally provide a testcase which illustrates the issue.
Henry
