### ISSUE TITLE
Is there a way to install LCOV locally in a directory other than /usr/local/?

### ISSUE THREAD

**Issue by shahmoradi** [linux-test-project/lcov#106]
Thank you for the great tool that you have developed. On supercomputers, write-access to /usr/local/bin/ is prohibited. This leads to LCOV installation failure in any possible way that I have tried. Is there a way to install LCOV locally in a path other than the default? Thank you in advance.

**Comment by henry2cox** [comment]
Assuming you unpacked the LCOV code to PWD:

  $ cd lcov
  $ make PREFIX=path_where_you_want_it_to_b install

I believe there is a readme (as well as a Makefile) which describes this.

**Comment by henry2cox** [comment]
I think this is resolved.
Closing.
