### ISSUE TITLE
Wrong function coverage

### ISSUE THREAD

**Issue by Diana-Lorena** [linux-test-project/lcov#107]
Hello!

Do you have any idea why I have some files with function coverage less than 100% when all the functions have been hit? It seems that gcov (or lcov?) treats some branches as functions, and unfairly decreases my function coverage. Is there a way of solving this? Any gcc flag that could help maybe? I attached an example to see how big the line coverage is, but still the function coverage is very low even though all the functions are hit.

Thanks!
![image](https://user-images.githubusercontent.com/62993766/102245528-57c7d600-3f06-11eb-9211-25114641645c.png)

**Comment by henry2cox** [comment]
This could be related to the issue I mentioned in #98.

If that is the same issue you see – then the workaround described there might help you.
(It did resolve the issues that I had noticed in our code base.)

Hope this helps
Henry

**Comment by Diana-Lorena** [comment]
Hei @henry2cox !

I studied the ticket but unfortunately the flags suggested there do not work. Also, what filters are described there? Could you give me a hint about what are those?

Thanks!

**Comment by henry2cox** [comment]
Filtering, differential coverage, annotations, etc – are implemented in the version of lcov that I branched.
I had submitted a pull request a few months back – but my changes haven’t been merged to master yet (and may never be merged to master).

I fear that you will have to try my version, if you want to use the feature….

Henry

**Comment by Diana-Lorena** [comment]
I cannot change the lcov version but thank you, I shall leave it as it is.
