### ISSUE TITLE
How to remove unreachable branches from coverage?

### ISSUE THREAD

**Issue by Diana-Lorena** [linux-test-project/lcov#108]
As far as I know, gcovr provides some flags that help in removing unreachable branches (--exclude-unreachable-branches). Is there something like this provided by lcov? I attach and example with the multiple branches detected by lcov for an if-else statement.
![image](https://user-images.githubusercontent.com/62993766/102355338-64a30300-3fb4-11eb-936e-a166555bd7a0.png)

**Comment by henry2cox** [comment]
Afraid you won’t like the answer ☺
Much like your previous issue – I had also implemented a ‘bogus branch filter’ feature (again, in my diffcov branch – pull request but not merged to master).

There is a moderately extensive discussion of the issues, limitations, etc. in issues #101 and #75 – as well as in the man page for the --filter option.

While I hope this is helpful – I suspect it is not.

Henry

**Comment by Diana-Lorena** [comment]
Ok, thanks :(

**Comment by henry2cox** [comment]
Maybe talk to your IT and/or install a personal copy of the tool – and see if it works for you or not?

Our IT is not always cooperative – but it is usually possible to get something installed…especially if you can claim that it is critical for some upcoming IP release ;-)
