### ISSUE TITLE
lcov fails for some gcno files with error:“ reached unexpected end of file”

### ISSUE THREAD

**Issue by Jackz-123** [linux-test-project/lcov#109]
I am using gcov and lcov to generate coverage report for my C++ code. While using lcov to generate the info file, for few files, I get the error as "reached unexpected end of file".

![izGC0](https://user-images.githubusercontent.com/20677089/102390022-ecf7c700-3ff9-11eb-9aa1-35ee700c32c5.png)

I found that there is a gcc bug in version 4.7 while generating gcno file. Below are the configurations I use:

1. redhat 64 bit - gcc 4.4.7 - lcov 1.12 -> of some 50+ gcno files, I get the error for 3 files
2. elinOS 64 bit - gcc 6.3.0 - lcov 1.12 -> of some 50+ gcno files, I get the error for 1 file
3. elinOS 32 bit - gcc 6.3.0 - lcov 1.12 -> I get no error here..

Would be great if you can provide any suggestion here..

**Comment by Jackz-123** [comment]
Any support??

**Comment by henry2cox** [comment]
Kind of hard to help you with no testcase and no real indication of what has happened.

The obvious suggestion is to use new(er) versions of tools - which appear to be working for you.
The obvious workaround is to wrap your 'capture' procedure inside a loop such that you watch for such error messages and remove the offending file(s) from your capture list (or simply delete the corresponding .gcno and .gcda files so they are not found by the next iteration).

**Comment by Jackz-123** [comment]
> Kind of hard to help you with no testcase and no real indication of what has happened. The obvious suggestion is to use new(er) versions of tools - which appear to be working for you. The obvious workaround is to wrap your 'capture' procedure inside a loop such that you watch for such error messages and remove the offending file(s) from your capture list (or simply delete the corresponding .gcno and .gcda files so they are not found by the next iteration).

Thank you for your reply.. I had already tried your work around and that worked for me. 

But would like to know the exact reason for the error reported by geninfo tool. When I tried to dump and check the .gcno file, I don't find anything special.. It is same like the the .gcno files that throws no error.. But,  It reaches unexpected end of file when I try to capture it using lcov..

**Comment by Jackz-123** [comment]
@henry2cox : I figured out the issue.. It was not related to the version of any of the tools..  But due to macro call.. In the files that gave me the issue, I had a macro call as the last line of code. It works as expected once I moved it to last but one line.. May be geninfo gets confused when a macro substitution comes as the last line of file..

**Comment by henry2cox** [comment]
I presume that the .gcno and/or .gcda files generated look different if there is a blank line at the end of file?
I will look again, but I don’t think ‘geninfo’ tries to read the source code (at least – not unless you are using my ‘diffcov’ version to implement filtering) – so it seems unlikely that the source difference is the problem.  Instead, I suspect that gcov is producing something malformed or unexpected.  If I knew what that was – I might be able to handle it gracefully.

**Comment by Jackz-123** [comment]
I think you are right.. It is the gcno file that differs and is related to the macro.. If I remove the macro, everything works fine and if I add it, lcov fails sometimes . I am not very sure of the reason..If I get some clue, will update here..
