### ISSUE TITLE
New 1.12 tag

### ISSUE THREAD

**Issue by jasperblues** [linux-test-project/lcov#11]
Hello, 

Is it possible to create  new 1.12 tag? We can then add recipes in MacPorts and Home Brew for Xcode 7 support

**Comment by oberpar** [comment]
I agree that it's time for a new release. I'll need a couple of days more though until I get to checking what files (changes, readme, etc.) need to be updated beyond the tag.

**Comment by jasperblues** [comment]
@oberpar that is fantastic - thank you. :clap:

**Comment by oberpar** [comment]
Tag + new release added.
