### ISSUE TITLE
`genpng` example

### ISSUE THREAD

**Issue by abitrolly** [linux-test-project/lcov#114]
[`genpng`](https://linux.die.net/man/1/genpng) man page mentions that this tool generates an overview image from source coverage. Is it just a rendered HTML? How does it looks like?

**Comment by oberpar** [comment]
It's not rendered HTML - just a mock-up of how a miniaturized version of the source code looks with colors.

See the following for an example:

http://ltp.sourceforge.net/coverage/lcov/output/example/methods/gauss.c.gcov.frameset.html

The image in the left frame is the output of `genpng`.

**Comment by abitrolly** [comment]
Thanks. Found it.

![image](https://user-images.githubusercontent.com/8781107/105058074-e8a24c00-5a86-11eb-9896-f6477ae367f8.png)

Some editors call it `minimap` and I guess it is taller for larger files. Not sure how to document it with `man`, which doesn't support graphics. Maybe mentioning where this image is used can give the point.

**Comment by henry2cox** [comment]
This appear to be resolved to everybody's satisfaction :-)
Closing now - in the interest of cleaning up the lcov issue list.
Henry
