### ISSUE TITLE
lcov 1.15 version get_version.sh source releases failing

### ISSUE THREAD

**Issue by wenzler** [linux-test-project/lcov#120]
Hey,

we were using automated downloads from http://downloads.sourceforge.net/ltp/lcov-${Version}.tar.gz"
And now saw that there's a redirect to a github tarball starting with version 1.15.

With this file the get_version.sh is falling back to release 1.0 as there is no .version file present
in the source release.

Compare https://github.com/linux-test-project/lcov/archive/refs/tags/v1.15.tar.gz
to https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz

BR
SW

**Comment by GitMensch** [comment]
Fixed with the release of 1.16 which distributes

```sh
VERSION=1.16
RELEASE=1
FULL=1.16
```

Isn't it?

**Comment by wenzler** [comment]
No more issue

**Comment by GitMensch** [comment]
Thanks for getting back, then please close the issue.
