### ISSUE TITLE
[enhancement] create a relocatable rpm for installation

### ISSUE THREAD

**Issue by XSven** [linux-test-project/lcov#126]
Background: I am working on a system that doesn't allow me to install lcov at the predefined place. I have checked the rpm package but this is not relocatable. Could you please provide a relocatable rpm, if possible? If for whatever reason this is not possible short-term, please describe a workaround. Thx.

**Comment by henry2cox** [comment]
You can also simply
   download/check out the code where you want to
   cd <where_I_downloade_it>/lcov
   make PREFIX=<where_I_want_it>  install
… which will install the scripts, the man pages, the examples.

Obviously – you will need write permission to the install location, and your customers will need execute permission (read permission as well, if they want to look at man pages or examples).

Henry

**Comment by XSven** [comment]
It is  pity but I cannot because the AIX _install_ script does not digest the -d and -p options and we are only allowed to extend the system using tools from the "AIX Toolbox for Linux Applications". I was not able to find the _install_ script there. I have tried to find replacement options  for -d and -p but I am getting other issues. So I am back to my original request: Please create a relocatable rpm.

**Comment by henry2cox** [comment]
FWIW:  I just checked in the changes to made my version of lcov build a relocatable RPM.
I suspect that that is a long way from what you actually need, though - as my branch would need to be merged to master, then a new RPM would need to be built and distributed by <somebody>.

**Comment by XSven** [comment]
Thanks for your effort so far. This issue can be treated with low priority. I have found a proper `install` program that belongs to the `coreutils` package. This package is part of the "AIX Toolbox for Linux Applications". I have managed to install lcov using `make install`. The only thing that I would like to mention is that 2 untracked zero byte files are now polluting the workspace

```
-rw-rw-r--    1 xxxxx    yyy               0 Aug 01 13:51 -t
-rw-rw-r--    1 xxxxx    yyy               0 Aug 01 13:51 202108011151.07
```

**Comment by henry2cox** [comment]
Where do you see those files?  (which directories?)
When I run (RHEL7 machine) – I do not seem to see any garbage created.

The one file looks like a timestamp name and the other, a misplace flag to some executable or script.  It might be an AIX artifact?  (I don’t have any way to test with AIX.

Henry

**Comment by XSven** [comment]
The problem is in `bin/updateversion.pl`. 

`system("touch", "$filename", "-t", $date[1]);`

The `touch` command available on AIX expects to have the options (like `-t`) first otherwise it treats them as usual files. I like this restriction, although these days tools offer the flexibility to mix options and arguments. I have now used the `touch` from the `coreutils` package and that works. Maybe it is still a good idea (for portability reasons) to change the order of arguments given to the `touch` command.

**Comment by henry2cox** [comment]
Good catch.
That seems easy enough to swap the ordr – so I modified my version.
(If I don’t do it right away – I will completely forget.)

Again, though:  not likely to help you or anyone else in the near term.
My branch would need to be merged back to master, then eventually released.  Long path.

Henry

**Comment by XSven** [comment]
I am fine with the current status and consider this issue as closed because you have completed the development although you did not create a new release.

Sven
