### ISSUE TITLE
subtract Coverage

### ISSUE THREAD

**Issue by 0x34d** [linux-test-project/lcov#135]
Is there any way to subtract two coverage report, 
And get a new output coverage.info file.

**Comment by henry2cox** [comment]
The answer depends on your application…exactly what are you trying to do, ultimately?

For example:  if you have 2 test suites – e.g., from ‘before’ and ‘after’ – and you want to know what lines/branches/functions were executed by one of them but not executed by the other – then “yes”.
This is the equivalent of treating the ‘hit’ count as a Boolean:  either zero (not hit) or larger than zeo (executed at least once) – and then subtracting to show “A & ~B” (“hit in A but not hit in B”), “~A & B” (“hit in B but not hit in A”), “A & B” (hit in both) – and so on.

You may be asking for actual integer subtraction of coverpoint hit counts:
  subtract the number of times that line L was hit in task A from the number of times it was hit in task B – so, if the line was hit 10 times in the first job but only 8 times in the second – your subtracted number would be “2”.
I don’t think you can do that out of the box – but it isn’t hard to write some perl code to do it - using the existing utilities.
I don’t understand what you would use the numbers for, though.  In particular, zero means either that the coverpoint was not exercised in either suite or was hit the same number of times in both – which seems not useful.  Similarly, both negative and positive numbers alias 2 cases each.

Presuming that the former is your goal – take a look at the ‘differential coverage’ pull request and/or the paper that it refers to.

If your application is different…could you explain a bit more – and perhaps we can help.

Henry

**Comment by 0x34d** [comment]
My goal is:
A =  Activate Application in idle condition.
B = Activate Application and hit input with it.
C (Report I want) = I need Which part of code was hit during input. by removing the initialization code in B based on A.

**Comment by henry2cox** [comment]
To clarify:

-          Lets say that we have a line which is hit twice during initialization, then hit once after initialization.

o   Hit count of that line in A will be 2

o   Hit count in B will be 3

Do you want the count in C to be 1 – or you want it to be zero (removed).

In other words:  are you looking for integer or Boolean operations on the ‘hit’ counts?

If you are looking for Boolean hit/not hit:  then you can try the differential coverage tool.
The code in the ‘GBC’ category is what you executed in B but not in A.
Assuming that you ran ‘lcov’ on experiments A and B to create corresponding .info files, then:
    $ genhml –o myDiff --baseline-file A.info --filter line,branch,function --branch-coverage --function-coverage – B.info
    $ google-chrome myDiff/index.html

If you are looking for integer subtraction:  you will need to write a small application (I’d base it on lcovutil.pm – but I may be biased).  Depending on how much error checking you want to do, this is a few tens of lines of code.
The .info file format is pretty simple – so you could also write something from scratch without a lot of difficulty.

If this is real-time or threaded code, or if it responds to interrupts – or really, anything more complicated than very simple sequential/serial code -  the exact ‘initialize’ trace might be different (different counts or entirely different paths) between experiments A and B.  The exact counts might not be comparable in practice.
(We see this, a lot.)

Sorry to be less than completely helpful.

Henry

**Comment by GitMensch** [comment]
This seems to be possible once #86 is implemented, correct? In this case please add this issue to its reference which will also auto-close the issue on merge.

**Comment by henry2cox** [comment]
Hi -
I think the answer to "..this seems to be possible once #86 is merged..." is either "yes" or "no" - depending on whether we interpret the issue to be requesting Boolean compare (then "yes") or integer difference ("no - but you can use some utilities to do that, even if I don't understand why you would want to") :-)
Personally, I think that only the Boolean compare makes sense.  YMMV.
(Also - #86 has been waiting for merge for 2 years - so I would not recommend holding your breath.
Might be easier to just grab the forked diffcov version.)
