### ISSUE TITLE
Create a report for each case

### ISSUE THREAD

**Issue by lirui311012** [linux-test-project/lcov#138]
I want to make a report for each case and only want to see the report for the files covered by this case and don't want the other reports

**Comment by henry2cox** [comment]
Will run very slowly and consume a lot of compute resource – but you can run each test using the GCOV_PREFIX feature to dump .gcda files in separate locations – then extract coverage reports from those separate locations, independently.

You should think about what you intend to do with all those reports, though.  My experience is that it is hard enough to get most people to look at even a single coverage report – leave alone dozens, hundreds, or tens of thousands of them.

Henry

**Comment by henry2cox** [comment]
No followup in over a year.
Presuming that suggested workaround was accepted/acceptable.
Closing this issue now

If there is still a problem, please either reopen this issue or file a new one.  Please include a detailed description of the problem, and include a testcase which exhibits the issue if possible.
I am trying to clean up the list of open issues to make it easier to see problems that still need to be addressed.
Henry
