### ISSUE TITLE
What do the versions in the version error mean?

### ISSUE THREAD

**Issue by simkoc** [linux-test-project/lcov#144]
I compiled the current SpiderMonkey using the mozbuild environment which ships a different gcc and corresponding libs than my operating system. After running a small sample program to test out the coder coverage I ran into the following error:

```
$ lcov --directory . --capture
Capturing coverage data from .
Found gcov version: 11.2.0
Using intermediate gcov format
Scanning . for .gcda files ...
Found 459 data files in .
Processing mozglue/misc/Mutex_posix.gcda
PATH/moz/mozilla-unified/codevalbuild/mozglue/misc/Mutex_posix.gcno:version '408*', prefer 'B12*'
geninfo: ERROR: GCOV failed for PATH/moz/mozilla-unified/codevalbuild/mozglue/misc/Mutex_posix.gcda!
```

I assume that this tells me that my local lcov cannot handle the generated coverage data due to a version mismatch. However, I am unable to map the displayed versions to the version of lcov on my system nor a previous version that could work.

``` 
$ lcov -v
lcov: LCOV version 1.15
```

Is there a table telling me how to translate `408*` and `B12* ` to a regular version number I could scour the net for or compile myself?

**Comment by latk** [comment]
The .gcno and .gcda files with coverage data contain the compiler version. The format of these files can change with each GCC release. You generated the .gcno file with GCC 4.x but lcov seems to be using the `gcov` utility from your system's GCC, which appears to be GCC 11.x. You can use the `lcov --gcov-tool` option to point to the gcov binary from the compiler you used – gcov is part of GCC.

**Comment by henry2cox** [comment]
As described by @latk:  lcov uses gcov under the hood to extract coverage data from the compile-time ".gcno" files and the runtime ".gcda" files.  Those data file are somewhat gcc-version dependent:  the gcov tool comes as part of the gcc toolsuite, and (in general) you need to use the same version of gcov as you did gcc.
gcov does some magic number checking to do some version compatibility checking.

LLVM is kind of similar - except that the tool is called 'llvm-cov' and you need to call it as "llvm-cov gcov ...." to get it to produce gcov-looking output (which can then be consumed by lcov and genhtml.

I rather suspect that the original issue reported by @simkoc is resolved ("use a compatible tool suite").
Thus:  I will close this report in a week or two, unless somebody reports that there is still a problem.
(Feel free to close the issue yourself, in the meantime.)

I'm trying to clean up the list of open issues to make it easier to see what the actual problems are.
Henry

**Comment by henry2cox** [comment]
No responses/no updates - so closing this issue.

If there is still a problem, please either reopen this issue or file a new one.  Please include a detailed description of the problem, and ideally include a testcase which exhibits the issue.
Henry
