### ISSUE TITLE
Inconsistency between line coverage and function hit numbers

### ISSUE THREAD

**Issue by schidamb-intel** [linux-test-project/lcov#145]
Hey folks, 
I'm trying to understand the gcov numbers from a project and seeing some inconsistency in the data:

Here's the function in my my_file.cc.gcov.html:
```
<a name="99"><span class="lineNum">      99 </span>            : bool</a>
<a name="100"><span class="lineNum">     100 </span><span class="lineCov">   11110200 : my_function_name(void) const</span></a>
<a name="101"><span class="lineNum">     101 </span>            : {</a>
<a name="102"><span class="lineNum">     102 </span><span class="lineCov">   11110200 :     return (smth_valid);</span></a>
<a name="103"><span class="lineNum">     103 </span>            : }</a>
<a name="104"><span class="lineNum">     104 </span>            : </a>
```

and the corresponding entry in the my_file.cc.func.html:
```
    <tr>
              <td class="coverFn"><a href="my_file.cc.gcov.html#98">my_function</a></td>
              <td class="coverFnLo">0</td>
            </tr>

```

Any idea why the function coverage displayed is 0, even though the line is hit 11110200 times? Trying to see where the bug is. 

Thanks! 
Sethu

**Comment by henry2cox** [comment]
Do you have a testcase that exhibits the problem?

**Comment by henry2cox** [comment]
Could you test this with the current TOT to see if the issue is resolved or not.
If it still exists:  do you have a testcase that illustrates the issue?

**Comment by henry2cox** [comment]
No response for 6 months.
Closing issue.

If this is still a problem:  please reopen or file a new issue.  Please include a detailed description of the problem and also include a testcase which exhibits the issue if possible.
Henry
