### ISSUE TITLE
Purpose of hyphen in BRDA info "taken" field?

### ISSUE THREAD

**Issue by RPGillespie6** [linux-test-project/lcov#148]
Hi, I tried searching through the lcov source on where hyphens in BRDA taken fields might originate, but I couldn't find anything. I see [conditionals ](https://github.com/linux-test-project/lcov/blob/master/bin/lcov#L2177) testing for it, but I can't see where it is generated, or why. Is the hyphen coming from gcov itself?

For example:
```
BRDA:237,0,0,-
BRDA:237,0,1,-
BRDA:293,0,0,-
BRDA:293,0,1,-
BRDA:415,0,0,-
BRDA:415,0,1,-
BRDA:452,0,1,-
BRDA:457,0,0,0
BRDA:457,0,1,0
BRDA:527,0,0,-
BRDA:527,0,1,-
BRDA:539,0,0,-
BRDA:539,0,1,-
```

I see parsers tend to treat hyphen as "zero": https://github.com/davglass/lcov-parse/blob/master/lib/index.js#L70 but there must be some extra meaning behind a hyphen or else zeros would always be used when dumping out the INFO file.

**Comment by henry2cox** [comment]
I confess to not remember this part  – but my comment in the code says:

        #   - $taken can be a number or '-'
        #     '-' means that the first clause of the branch short-circuited -
        #     so this branch was not evaluated at all.
        #     In any branch pair, either all should have a 'taken' of '-'
        #     or at least one should have a non-zero taken count and
        #     the others should be zero.

Hope that helps.
(Also hope it is correct 😊

Henry

**Comment by RPGillespie6** [comment]
Ah, that does clarify things. Thanks, much appreciated!

**Comment by oberpar** [comment]
The file format is also described in the geninfo man page:
```
$ man geninfo
...
      BRDA:<line number>,<block number>,<branch number>,<taken>

       Block  number  and  branch  number are gcc internal IDs for the branch.
       Taken is either '-' if the basic block containing the branch was  never
       executed or a number indicating how often that branch was taken.
```
