### ISSUE TITLE
Default install path conflicts with distro packages

### ISSUE THREAD

**Issue by cha5on** [linux-test-project/lcov#15]
Per the Filesystem Hierarchy Standard, Version 2.2 ⟨http://www.pathname.com/fhs/), programs that are local to the site are typically installed to /usr/local/ .  However, the Makefile installs by default to /usr/bin and /usr/share/doc .  This means that by default, building from source will not "play nice" with distribution packages of lcov.

Changing the default install prefix to /usr/local will help to alleviate this problem and make installing from source friendlier to novices who might not realize that this could mess with their distribution's installed packages.

**Comment by oberpar** [comment]
Should be fixed with commit 68320d932c5ee5537ae1c287fe52603ae2fecf8c. Thanks for reporting!
