### ISSUE TITLE
Request for LCOV 1.16 release

### ISSUE THREAD

**Issue by GitMensch** [linux-test-project/lcov#150]
Giving the [differences since 1.15](https://github.com/linux-test-project/lcov/compare/v1.15...master) (and especially the two new options for "dark mode" and the more important "fail below percentage") it would be nice to get a new release.

Is there anything else missing other than adjusting the README (which still points to the SF page)?
Would it help to send a PR for adjusting the README? Should it be changed to markdown, too?

**Comment by oberpar** [comment]
Version 1.16 has just been released. Thanks for your input!
