### ISSUE TITLE
"static" line not stats

### ISSUE THREAD

**Issue by peiwenz2** [linux-test-project/lcov#159]
Hi, I'm using lcov & gcov to generate coverage report. Everything goes fine except the "static" code line.

I found the static line will never be counted and it does influence the remaining part of the function:
![image](https://user-images.githubusercontent.com/110538780/182600989-625f2f0d-073d-490a-9259-c1fbf1d05179.png)
See this pic, the "break" line is hitted whereas other lines are not in this if condition.(its impossible)

And after I remove the "static", everything works just fine.
![image](https://user-images.githubusercontent.com/110538780/182600760-029c4b0a-0472-44ec-a8a7-ff74b14b516c.png)

..........totally messed up in this situation, can u help me out? what's the matter with static? why its not a efficient code line?

**Comment by henry2cox** [comment]
The compiler noticed that the data was unchanging - so it got inserted into your code as a constant (address into static string).
Think of it as "the assignment happened at compile time (not at runtime) - and the coverage tool only measures what happened at runtime".

You can see a similar thing, if you happen to use a static const, template parameter, or macro in an if/else statement.
There is an excellent chance that the compiler will notice that one or the other branch is statically unreachable (in this configuration) - and remove the code.  You won't see branch data on the conditional, and you won't see statement data for the part that got removed.  This is quite similar to what happens if you have a #if-#else-#endif block in your C/C++ code.
Hope that helped.
Henry

**Comment by peiwenz2** [comment]
> 

thanks Hnery. Really helpful. I can understand why static not reachable by cov.
But still one confusion, why this "break" marked hitted?

**Comment by henry2cox** [comment]
That looks like a line numbering/version issue.
I suspect that you might have gcov data extracted for one source code version, displayed for another.

Check (carefully) that you have cleaned up .o, .gcda, .gcno files – then rebuild and rerun.

If the issue persists:  then this is either a gcov or lcov bug (more likely gcov, as lcov is just displaying the data extracted by gcov).
In that case:
  - what version of gcc, gcov, binutila are you using?
  - what platform (redhat, ubuntu, something else?) and version
  - provide testcase that illustrates the issue.  (Likely that no one can debug without a testcase – sorry.)

Henry

**Comment by peiwenz2** [comment]
> That looks like a line numbering/version issue. I suspect that you might have gcov data extracted for one source code version, displayed for another. Check (carefully) that you have cleaned up .o, .gcda, .gcno files – then rebuild and rerun. If the issue persists: then this is either a gcov or lcov bug (more likely gcov, as lcov is just displaying the data extracted by gcov). In that case: - what version of gcc, gcov, binutila are you using? - what platform (redhat, ubuntu, something else?) and version - provide testcase that illustrates the issue. (Likely that no one can debug without a testcase – sorry.) Henry

Hi Henry, thanks for ur quick reply. I have checked the code directory, it's totally the same...

We do run tests in a distributed system which send cases to different k8s pods to execute, and gather results to one main pod to generate final report(coverage res generate there). However, we use NFS to keep the code and binaries, that is, for one CI job, the code only saved in ONE NFS directory. So, it's impossible that we use two different code repository....

Also, we are running DAILY test, and everyday, this "break" is hitted.... Sadly, I believe this more like to be a bug....

We are using gcc4.9.2 / gcov 2.17 / ld version GNU ld version 2.27-34 on a Linux Platform.

For testcases, I may try to write a similar case this week and back to you....(Sorry we have a huge code repo and this is just a func in a file)

**Comment by henry2cox** [comment]
No problem.

When you get to it, you get to it.
This may or may not be important, depending on your methodology.

(We have a pretty large code base too – with shared modules that are used in multiple different projects – so version drift does happen more than you might like.  I had added a few features to make it work better – or at least, to find issues if they happen.
I have not see the specific issue you report – but it is possible that it happened somewhere and our automation just did not notice.)

4.9 is pretty old.
You might try upgrading to a newer gcc and newer gcov, if you can.
That might not be possible, and might not resolve the issue, even if it is possible.

Henry

**Comment by xaizek** [comment]
This is likely to be a debug information issue. Even when compiled without optimizations, some instructions can be shuffled around, in the process they sometimes lose associated debug information or get information from other lines. Ideally, compilers won't do this, but it's easier said than done.

You can try compiling with `-g -S` and inspecting assembly. There will be directives like `.file "name"`. and `.loc 1245` which mark instructions with line number information. In this case, that `break;` might have been merged with some code generated by the compiler, so that when that code is run it looks like your code is executed.

**Comment by henry2cox** [comment]
Ah.  Makes sense.  I did not think of that.

That could be another reason that moving to a newer gcc might resolve the issue… some debuginfo bugs may have been fixed.
Of course – a new version might just have different issues 😊

If you _do_ try a newer gcc – it can be interesting/illuminating to generate a differential coverage report with your gcc/4.9 data as you ‘baseline’ and your new report as ‘current’.
That report will highlight all the places where the different gcc releases claim different coverpoints and/or different coverages.
The source code is unchanged – so everything you see is down to compiler/toolchain differences.

**Comment by peiwenz2** [comment]
> This is likely to be a debug information issue. Even when compiled without optimizations, some instructions can be shuffled around, in the process they sometimes lose associated debug information or get information from other lines. Ideally, compilers won't do this, but it's easier said than done.
> 
> You can try compiling with `-g -S` and inspecting assembly. There will be directives like `.file "name"`. and `.loc 1245` which mark instructions with line number information. In this case, that `break;` might have been merged with some code generated by the compiler, so that when that code is run it looks like your code is executed.
> 
> **Edit:** Wait, coverage isn't guided by DWARF, but by counters incremented in the code:
> 
> ```assembly
> 	movq	__gcov0._Z16gothroughnumbersv+8(%rip), %rax
> 	addq	$1, %rax
> 	movq	%rax, __gcov0._Z16gothroughnumbersv+8(%rip)
> ```
> 
> However, the situation is not much different with these: after counters are inserted changes to assembly might make them react to executtion of unrelated code. Inspecting final assembly can still show something.

Thanks a lot, will look deeper into compiler for this problem. Have not thought of that before, really inspiring! thanks

**Comment by peiwenz2** [comment]
> Ah. Makes sense. I did not think of that. That could be another reason that moving to a newer gcc might resolve the issue… some debuginfo bugs may have been fixed. Of course – a new version might just have different issues 😊 If you _do_ try a newer gcc – it can be interesting/illuminating to generate a differential coverage report with your gcc/4.9 data as you ‘baseline’ and your new report as ‘current’. That report will highlight all the places where the different gcc releases claim different coverpoints and/or different coverages. The source code is unchanged – so everything you see is down to compiler/toolchain differences.

Yeah we are trying to update our gcc version from 492 to 921. Still trying since the libs we are using are all built by gcc492, as well....... :( 

haha gonna back to you if the problem still exist after we upgrade gcc. Thanks
