### ISSUE TITLE
geninfo incompatible with LLVM gcov 8.0

### ISSUE THREAD

**Issue by aleks-p** [linux-test-project/lcov#16]
The update to XCode 8.0 seem to brought an issue similar to https://github.com/linux-test-project/lcov/issues/10.

The behavior we get is:

    $ lcov --capture --no-external --initial --base-directory packages --directory . --output-file ./report.init
    Capturing coverage data from .
    Scanning . for .bb files ...
    geninfo: WARNING: no .bb files found in . - skipping!
    Finished .info-file creation

Version of lcov and gcov:

    $ gcov --version
    Apple LLVM version 8.0.0 (clang-800.0.38)
    $ lcov --version
    lcov: LCOV version 1.12

**Comment by oberpar** [comment]
I cannot seem to reproduce this issue. When I feed the quoted output of "gcov --version" into lcov 1.12, all other command line parameters being the same, I get the following correct output:

Capturing coverage data from .
Found gcov version: 8.0.0
Found LLVM gcov version 3.4, which emulates gcov version 4.2
Scanning . for .gcno files ...
geninfo: WARNING: no .gcno files found in . - skipping!
Finished .info-file creation

Could it be that a different gcov-tool is being used (maybe check lcovrc files or specify the gcov tool using --gcov-tool <path-to>/gcov).

**Comment by aleks-p** [comment]
I seem to have 3 different installations of gcov:

    $ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gcov --version
    Apple LLVM version 8.0.0 (clang-800.0.38)

    $ /Library/Developer/CommandLineTools/usr/bin/gcov --version
    LLVM (http://llvm.org/):
      LLVM version 7.3.0

    $ /usr/bin/gcov --version
    Apple LLVM version 8.0.0 (clang-800.0.38)

Running the same command as above, with specifying the --gcov-tool parameter works fine when using the llvm.org one (LLVM version 7.3.0) and produces the same error as before when using the other 2 (Apple LLVM) versions.

**Comment by aleks-p** [comment]
I believe the problem is at this line in geninfo:

`$version_string = $pipe_next_line if ($pipe_next_line && $version_string =~ /LLVM/);`

In the case of Apple LLVM the first line of the version actually contains LLVM, and geninfo takes the second line which in this case is "Optimized build.".

**Comment by oberpar** [comment]
You  mentioned a second line in the output of --version, but I don't see one in the Apple examples you posted. Could you post the complete output of gcov --version for those cases where lcov fails? You're assumption about the cause of the problem is likely correct, but I like to have full input data to verify that a fix will work.

**Comment by aleks-p** [comment]
yes, apologies for that, I didn't think at the time that it is relevant but it actually is:

    $ /usr/bin/gcov --version
    Apple LLVM version 8.0.0 (clang-800.0.38)
      Optimized build.
      Default target: x86_64-apple-darwin16.0.0
      Host CPU: haswell

**Comment by oberpar** [comment]
I've reworked the version detection somewhat. Please have a look at d7cc7591b3a7cc1ec95371d04e4fc46f10b3fd54 to see if it fixes the issue that you are seeing. Thanks!

**Comment by aleks-p** [comment]
It looks like the change fixes the issue, thanks.

**Comment by oberpar** [comment]
Thank you for testing.

**Comment by justinjohn83** [comment]
Thanks this fix also worked for me with XCode 8.1
