### ISSUE TITLE
genhtml  - feature request - all files on one page

### ISSUE THREAD

**Issue by sdarwin** [linux-test-project/lcov#165]
Hi,
We have a request to "view all files in all directories recursively and sort them" in the html output of genhtml. This is after running lcov on a C++ project.  So instead of displaying a directory structure where you must click and drill down to each directory, just list all files on a single page.    
Does that sound like an interesting option? Would it be difficult to implement?

**Comment by sdarwin** [comment]
@henry2cox great info. thanks!
> to see on a single screen
You could scroll, or click Ctrl-F to find on page.

**Comment by henry2cox** [comment]
*   You could scroll, or click Ctrl-F to find on page.

Indeed, you could.
That starts to get to the slippery slope of “hmm…if I search for <path>, then I can find all the files in <directory> that I actually care about” -
and then we are quickly back to wanting a directory-level or hierarchical view. 😉

Everyone is different – and it is impossible to know how particular users will actually apply the tools.  Things I find not-so-helpful might be critically important to someone else, and vice versa.
I’m usually happy just to know that some team is using the tools – and so appears to be trying to improve their verification methodology.

**Comment by sdarwin** [comment]
>  slippery slope 

Sure, but it's only an option not a requirement. We probably have, as you say, a smaller project, and not 1000's of files.

**Comment by henry2cox** [comment]
*   Sure, but it's only an option not a requirement.

Yep.  But also a time investment (to merge and/or enhance and/or re-implement the feature, as well as ongoing verification and maintenance).
Needs to be prioritized vs. other tasks.

  *   We probably have, as you say, a smaller project, and not 1000's of files.

Probably number of distinct teams is more important than number of files (though the one is correlated with the other).
Particular teams or individuals tend to care about particular modules – and those modules are often reflected in the directory structure as well as developer name and group(s).

Fundamentally, I think that we are in violent agreement:  any use model (and corresponding set of features) that is working for someone is a good use model 😊
You don’t get far by trying to force change.  The team typically understands what they need better than outsiders do.
Yet another key is to enable a path from relatively simple to more sophisticated/more automated ones.

**Comment by henry2cox** [comment]
added feature "genhtml --flat ..." in SHA 36754c884deb4c.  Turned out to be easier than anticipated.
Please take a look and see if it does what you need.
If yes:  please close this issue.  If no, please elaborate what is missing. 
Thanks
Henry

**Comment by sdarwin** [comment]
Got it working after a few attempts.

- "--ignore-errors unused" was needed in many places.
- libcapture-tiny-perl libdatetime-perl libdatetime-format-dateparse-perl must be installed.

Yes, the results look nice. That's great.

How about re-clicking on "Line Coverage" or "Functions" to re-sort ascending or descending?

Very glad to have the feature added. I will close the issue.

**Comment by henry2cox** [comment]
The various sorting features should be working – similarly, differential categorization, etc.
Flat/hierarchical/traditional display should be orthogonal to all the other features.
If this is not the case – then it is a bug that needs to be fixed.

The ‘unused’ errors should not be generated unless you have specified an include/exclude/subst pattern that could not be applied to anything.
The reason that is an error is that it indicates an “error of understanding”:  you thought that the pattern was meaningful (or you would not have specified it).
That it did not apply means either that you have a typo, or the code we are looking at is not the code you think we are looking at – so any report we generate will be misleading at best, and dead wrong at worst.  We use this tool for verification…we cannot be making undetected errors or wrong assumptions.
If you are seeing bogus messages – then that is a bug that needs to be fixed.

Package requirements are mentioned in the “README” -
It might be useful if you added a small section to explain what you had to do to install them on your platform – as others are likely to have the same issues and might need help to figure it out.
(On <my platform>, I installed the required packages via “….”)
Documentation and test PRs will get priority😊

In any case:  glad it is working for you.

Henry
