### ISSUE TITLE
Add 1.16.0 to chocolatey repository

### ISSUE THREAD

**Issue by bavovanachte** [linux-test-project/lcov#166]
Hi,

Currently the latest version available on chocolatey is 1.15.0, could 1.16.0 be uploaded there as well?

Thanks!

**Comment by bollenn** [comment]
:+1:

**Comment by henry2cox** [comment]
I fear that I don't know what is involved in getting something into that repo - but please feel free to do so.
In an effort to clean up the open issue list, I'm going to close this issue as it seems not related to lcov.
Feel free to reopen (hopefully, with a suggested list of concrete actions which should be taken).

Thanks
Henry
