### ISSUE TITLE
How to negate filtering pattern for lcov --remove? Is there --keep?

### ISSUE THREAD

**Issue by fuzzah** [linux-test-project/lcov#170]
Hi!
Let's say we have a lot of source files.
Simplified example:
```
aaa/bbb/source1.c
aaa/bbb/source2.c
aaa/bbb/ccc/source3.c
aaa/bbb/ccc/source4.c
bbb/source5.c
ccc/source6.c
ddd/eee/source7.c
```
And let's imagine we only need aaa/bbb/ccc/*.c in our HTML report.

Is there a convenient way to only keep sources under aaa/bbb/ccc?

I think the options would be:
1) stubbornly enumerate `--remove` patterns for everything that is not under aaa/bbb/ccc - let's not consider this an option, because it's too much of a work
2) somehow negate the single `--remove` pattern, but I don't know how
3) use some sort of `--keep` option, but I fail to find such thing in lcov

**Comment by henry2cox** [comment]
Once PR #169 is merged - then you can use either the "--include" or "--exclude" options to do what you want in the genhtml command itself.
At present:  you can use either "lcov --remove' (to remove the ones you don't want) or 'lcov --extract' (to keep the ones you do want).  You build a new .info file from the one you have - then generate a report from that new one.
The patterns use glob matching, and must match the entire path.
In your case, it looks like something similar to
   lcov -o myNewReport.info --extract myOrig.info  'aaa/bbb/ccc/*.c'
is probably sufficient.

Hope that helps.
Henry

**Comment by fuzzah** [comment]
@henry2cox 

> --extract

Thank you! I somehow skipped this option in --help...
