### ISSUE TITLE
Some lines are not recognized as valid in gcc9,

### ISSUE THREAD

**Issue by Prines** [linux-test-project/lcov#177]
Some lines are not recognized as valid in gcc9, but can be recognized by gcc492, code is same. Such as
 "struct RepDataSyncCtx{}",   
"     #ifdef APSARA_UNIT_TEST_MAIN
      ChunkServerService() : PeriodicalTask(1000) {}   "
etc. 

picture1 is gcc492 coverage, picture2 is gcc921 coverage.

![20221208102737](https://user-images.githubusercontent.com/33364066/206341473-678511c5-bfda-4dfe-8737-b06be3f90882.jpg)

![20221208102620](https://user-images.githubusercontent.com/33364066/206341343-8ebf86e7-e440-4cdb-a08e-95f924e606cb.jpg)

**Comment by henry2cox** [comment]
It looks very much like those lines are ifdef'd out in your gcc9 build.
Can you try adding
   # error "test if gcc9 sees this code"
within the #ifdef/#endif block - and see if your build crashes or not.  I suspect not.
In either case:  I think that this is unlikely to be an lcov issue.  Lcov is just looking at data found in the .gcda files (as reported by gcov) - so if this is not just an #ifdef misunderstanding, then it is very likely a gcc or gcov issue.

If your application is released on multiple platforms and/or with multiple tool chains, then you might want to generate and merge all those reports into a single unified report.  You likely also want individual toolchain/platform reports as well; your project manager will use them for slightly different purposes.

As an aside:  you might want to add "--filter branch" to your "lcov --capture" or genhtml command line.
All those branches look like compiler-generated exception handling glue - and you very likely don't care that half of them are not taken.

Hope this helps
Henry
