### ISSUE TITLE
"Overlong record at end of file!" and "geninfo: No JSON module found (tried JSON::XS Cpanel::JSON::XS JSON::PP JSON)"

### ISSUE THREAD

**Issue by nguthrie** [linux-test-project/lcov#180]
When `geninfo_intermediate = 0` in `/etc/lcovrc`, I get `Overlong record at end of file!`. 

When `geninfo_intermediate = auto`, I get `geninfo: No JSON module found (tried JSON::XS Cpanel::JSON::XS JSON::PP JSON)`. This is surprising because I've used `gcov --json-format app.cpp` to generate `app.cpp.gcov.json.gz`.  After decompressing it to `app.cpp.gcov.json`, there is a JSON file available in the directory. Contents of the `gcov` JSON file for a simple Hello World program:
```
{"gcc_version": "10.2.1 20210130 (Red Hat 10.2.1-11)", "files": [{"lines": [{"branches": [], "count": 2, "line_number": 4, "unexecuted_block": false, "function_name": "main"}, {"branches": [], "count": 2, "line_number": 5, "unexecuted_block": false, "function_name": "main"}, {"branches": [], "count": 2, "line_number": 6, "unexecuted_block": false, "function_name": "main"}], "functions": [{"blocks": 3, "end_column": 1, "start_line": 4, "name": "main", "blocks_executed": 3, "execution_count": 2, "demangled_name": "main", "start_column": 5, "end_line": 7}], "file": "helloworld.cpp"}], "format_version": "1", "current_working_directory": "/home/qa/coverage_testing", "data_file": "helloworld.cpp"}
```

Any advice on how to proceed?

`lcov: LCOV version 1.16`
`gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)`

```
NAME="CentOS Linux"
VERSION="7 (Core)"
```

**Comment by henry2cox** [comment]
Can you try your testcase again with current TOT (not the released module).
There have been quite a few changes recently – so this may (or may not) already be fixed.

Thanks

Henry

**Comment by nguthrie** [comment]
Hi Henry, thank you kindly for the quick response. I did as you suggested but got the same, albeit more verbose, result:
```
$ lcov --version
lcov: LCOV version v1.16-15-g218beb0
$ lcov -d .. -c -o new.info
Capturing coverage data from ..
geninfo cmd: '/usr/local/bin/geninfo .. --output-filename new.info --parallel 1 --memory 0'
Found gcov version: 4.8.5
Writing temporary data to /tmp/geninfo_datXRAj
Scanning .. for .gcda files ...
Found 1 data files in ..
Processing helloworld.gcda
geninfo: WARNING: /home/qa/coverage_testing/helloworld.gcno: Overlong record at end of file!
geninfo: WARNING: gcov did not create any files for /home/qa/coverage_testing/helloworld.gcda!
Finished .info-file creation
```

**Comment by henry2cox** [comment]
hmm.
I just re-ran the lcov regression suite with gcc/4.8.5 - which is the version I think you are using.  (Fortunately, present on the systems :-))
They all ran successfully...which is good and bad.  Yes - all the tests passed - but we know that the test coverage is weak.

Can you try the same.
  - from your downloaded version of the lcov project, run "make clean ; make test" from the top-level directory.  Let's see what fails - if anything fails.
  - also, try running your testcase again, as "lcov -d .. -c -o new.info _**-v -v -debug -debug**_"  (i.e., turning up verbosity)

Thanks.
Henry

**Comment by nguthrie** [comment]
Thank you for looking into it again. 

I'm using `gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)` (I also found that `lcov 1.16` works fine on `gcc/4.8.5` and `gcc/8` but not on `gcc/9` or `gcc/`10`). 
Running 
`lcov -d .. -c -o new.info -debug -debug -debug` in a directory containing 
```
a.out  helloworld.cpp  helloworld.gcda  helloworld.gcno
```
gives the following:
```
Capturing coverage data from .
DEBUG: LCOV version 1.16
Found gcov version: 10.2.1
DEBUG: gcov has capability 'all-blocks'
DEBUG: gcov has capability 'branch-probabilities'
DEBUG: gcov has capability 'branch-counts'
DEBUG: gcov has capability 'display-progress'
DEBUG: gcov has capability 'function-summaries'
DEBUG: gcov has capability 'json-format'
DEBUG: gcov has capability 'human-readable'
DEBUG: gcov has capability 'use-colors'
DEBUG: gcov has capability 'long-file-names'
DEBUG: gcov has capability 'demangled-names'
DEBUG: gcov has capability 'no-output'
DEBUG: gcov has capability 'preserve-paths'
DEBUG: gcov has capability 'use-hotness-colors'
DEBUG: gcov has capability 'relative-only'
DEBUG: gcov has capability 'source-prefix'
DEBUG: gcov has capability 'stdout'
DEBUG: gcov has capability 'unconditional-branches'
DEBUG: gcov has capability 'verbose'
DEBUG: gcov has capability 'hash-filenames'
Scanning . for .gcda files ...
Found 1 data files in .
Processing helloworld.gcda
DEBUG: expecting file magic
DEBUG: read(4)=4: 6f 6e 63 67  |oncg|
DEBUG: expecting compiler version
DEBUG: read(4)=4: 52 32 30 42  |R20B|
DEBUG: found version 0x000a0200
DEBUG: expecting file timestamp
DEBUG: read(4)=4: d0 0a e9 12  |....|
DEBUG: expecting support unexecuted blocks flag
DEBUG: read(4)=4: 09 00 00 00  |....|
DEBUG: expecting record tag
DEBUG: read(4)=4: 2f 68 6f 6d  |/hom|
DEBUG: expecting record length
DEBUG: read(4)=4: 65 2f 71 61  |e/qa|
DEBUG: Overlong record: file_length=328 rec_length=6539230612
geninfo: WARNING: /home/qa/coverage_testing/test-9/helloworld.gcno: Overlong record at end of file!
DEBUG: chdir(/home/qa/coverage_testing/test-9)
DEBUG: system(gcov /home/qa/coverage_testing/test-9/helloworld.gcda -o /home/qa/coverage_testing/test-9 -b -x)
geninfo: WARNING: cannot find an entry for helloworld.cpp##eee8813e1c41aae46e1c25f25175a955.gcov in .gcno file, skipping file!
Finished .info-file creation
[qa@yvr-perf_ex-lt1 test-9]$ ls
a.out  helloworld.cpp  helloworld.gcda  helloworld.gcno  new.info
[qa@yvr-perf_ex-lt1 test-9]$ rm new.info
[qa@yvr-perf_ex-lt1 test-9]$ ls
a.out  helloworld.cpp  helloworld.gcda  helloworld.gcno
[qa@yvr-perf_ex-lt1 test-9]$ lcov -d . -c -o new.info -debug -debug -debug
Capturing coverage data from .
DEBUG: LCOV version 1.16
Found gcov version: 10.2.1
DEBUG: gcov has capability 'all-blocks'
DEBUG: gcov has capability 'branch-probabilities'
DEBUG: gcov has capability 'branch-counts'
DEBUG: gcov has capability 'display-progress'
DEBUG: gcov has capability 'function-summaries'
DEBUG: gcov has capability 'json-format'
DEBUG: gcov has capability 'human-readable'
DEBUG: gcov has capability 'use-colors'
DEBUG: gcov has capability 'long-file-names'
DEBUG: gcov has capability 'demangled-names'
DEBUG: gcov has capability 'no-output'
DEBUG: gcov has capability 'preserve-paths'
DEBUG: gcov has capability 'use-hotness-colors'
DEBUG: gcov has capability 'relative-only'
DEBUG: gcov has capability 'source-prefix'
DEBUG: gcov has capability 'stdout'
DEBUG: gcov has capability 'unconditional-branches'
DEBUG: gcov has capability 'verbose'
DEBUG: gcov has capability 'hash-filenames'
Scanning . for .gcda files ...
Found 1 data files in .
Processing helloworld.gcda
DEBUG: expecting file magic
DEBUG: read(4)=4: 6f 6e 63 67  |oncg|
DEBUG: expecting compiler version
DEBUG: read(4)=4: 52 32 30 42  |R20B|
DEBUG: found version 0x000a0200
DEBUG: expecting file timestamp
DEBUG: read(4)=4: d0 0a e9 12  |....|
DEBUG: expecting support unexecuted blocks flag
DEBUG: read(4)=4: 09 00 00 00  |....|
DEBUG: expecting record tag
DEBUG: read(4)=4: 2f 68 6f 6d  |/hom|
DEBUG: expecting record length
DEBUG: read(4)=4: 65 2f 71 61  |e/qa|
DEBUG: Overlong record: file_length=328 rec_length=6539230612
geninfo: WARNING: /home/qa/coverage_testing/test-9/helloworld.gcno: Overlong record at end of file!
DEBUG: chdir(/home/qa/coverage_testing/test-9)
DEBUG: system(gcov /home/qa/coverage_testing/test-9/helloworld.gcda -o /home/qa/coverage_testing/test-9 -b -x)
geninfo: WARNING: cannot find an entry for helloworld.cpp##eee8813e1c41aae46e1c25f25175a955.gcov in .gcno file, skipping file!
Finished .info-file creation
```
 Running the following `lcov -d . -c -o new.info -debug -debug` gives
```
Capturing coverage data from .
DEBUG: LCOV version 1.16
Found gcov version: 10.2.1
DEBUG: gcov has capability 'all-blocks'
DEBUG: gcov has capability 'branch-probabilities'
DEBUG: gcov has capability 'branch-counts'
DEBUG: gcov has capability 'display-progress'
DEBUG: gcov has capability 'function-summaries'
DEBUG: gcov has capability 'json-format'
DEBUG: gcov has capability 'human-readable'
DEBUG: gcov has capability 'use-colors'
DEBUG: gcov has capability 'long-file-names'
DEBUG: gcov has capability 'demangled-names'
DEBUG: gcov has capability 'no-output'
DEBUG: gcov has capability 'preserve-paths'
DEBUG: gcov has capability 'use-hotness-colors'
DEBUG: gcov has capability 'relative-only'
DEBUG: gcov has capability 'source-prefix'
DEBUG: gcov has capability 'stdout'
DEBUG: gcov has capability 'unconditional-branches'
DEBUG: gcov has capability 'verbose'
DEBUG: gcov has capability 'hash-filenames'
Scanning . for .gcda files ...
Found 1 data files in .
Processing helloworld.gcda
DEBUG: expecting file magic
DEBUG: read(4)=4: 6f 6e 63 67  |oncg|
DEBUG: expecting compiler version
DEBUG: read(4)=4: 52 32 30 42  |R20B|
DEBUG: found version 0x000a0200
DEBUG: expecting file timestamp
DEBUG: read(4)=4: d0 0a e9 12  |....|
DEBUG: expecting support unexecuted blocks flag
DEBUG: read(4)=4: 09 00 00 00  |....|
DEBUG: expecting record tag
DEBUG: read(4)=4: 2f 68 6f 6d  |/hom|
DEBUG: expecting record length
DEBUG: read(4)=4: 65 2f 71 61  |e/qa|
DEBUG: Overlong record: file_length=328 rec_length=6539230612
geninfo: WARNING: /home/qa/coverage_testing/test-9/helloworld.gcno: Overlong record at end of file!
DEBUG: chdir(/home/qa/coverage_testing/test-9)
DEBUG: system(gcov /home/qa/coverage_testing/test-9/helloworld.gcda -o /home/qa/coverage_testing/test-9 -b -x)
geninfo: WARNING: cannot find an entry for helloworld.cpp##eee8813e1c41aae46e1c25f25175a955.gcov in .gcno file, skipping file!
Finished .info-file creation
```
(Running the command with `-v` as an argument returned version info.)

**Comment by nguthrie** [comment]
I get the same result using `LCOV version v1.16-15-g218beb0`

**Comment by oberpar** [comment]
Using lcov with `geninfo_intermediate = 0` is not supported for GCC versions 9 and above - lcov's `.gcno`-file parsing function was never updated to understand the `.gcno` file format of GCC 9 and above. See also commit 75fbae1cfc5027f818a0bb865bf6f96fab3202da. If I understand your initial report correctly, the following error message may be the source of your problems when using `geninfo_intermediate = auto`:

```
geninfo: No JSON module found (tried JSON::XS Cpanel::JSON::XS JSON::PP JSON)
```

It appears that you have none of the supported Perl JSON parsing modules installed on your system. The fix would therefore be the installation of such a module (either of the ones listed in the error message would do).

**Comment by henry2cox** [comment]
Ah - thanks Peter.  
Yet another thing I did not know :-)
Helps to have context.

I'll look into adding a check for gcov version - and then error out if settings are not supported.
(I will close this issue when that error check is in place...but feel free to reopen it, and even more, to add support for parsing the newer text formats.  Happy to merge the corresponding PR.)

Henry

**Comment by nguthrie** [comment]
Hi Henry and Peter, that solved the issue! Thank you!

**Comment by nguthrie** [comment]
A possible suggestion would be to make the error message more user-friendly for non-Perl users :)

**Comment by oberpar** [comment]
> A possible suggestion would be to make the error message more user-friendly for non-Perl users :)

Yes, I thought about the same. How about:

```
geninfo: No Perl JSON module found - please install one of the following Perl modules:
JSON::XS Cpanel::JSON::XS JSON::PP JSON
```

**Comment by henry2cox** [comment]
Maybe we should also add a "prerequites" section to the README - to say which packages and versions are required.
(Yeah - nobody reads documentation...so clear warning and error messages are also essential :-) )

**Comment by henry2cox** [comment]
I added the check mentioned above.  When I run a test in my sandbox, I now see:
> $ ./bin/geninfo . -o x.info --config-file testrc
Found gcov version: 10.2.0
geninfo: Error: geninfo does not support text format for gcov/9 or higher (your version appears to be 'gcov  10.2.0').
  Please remove config file entry 'geninfo_intermdediate = 0'.
        (use "geninfo --ignore-errors unsupported ..." to bypass this error)

... which is 1/2 of the above battle.
I will check this in along with some other enhancements after I finish testing everything.
That very likely won't happen until next year

**Comment by henry2cox** [comment]
FWIW:  I also added the error message:
 >No Perl JSON module found on your system.  Please install of of the following supported modules: JSON::XS Cpanel::JSON::XS JSON::PP JSON - for example (as root)
    $ perl -MCPAN -e 'install JSON::XS'

I'll check that in along with everything else.

**Comment by henry2cox** [comment]
pushed the above checks and messages to  038c2ca22598bf645436806ecb5f16716a29b513.
Please take a look and then close this issue, if you think we are in good shape.
Thanks
Henry

**Comment by henry2cox** [comment]
> Note: I did NOT add a prerequisites section to the README - so perhaps this issue isn't entirely done yet.

SHA 7ae5e15d94d1 add a 'Dependencies' section to the README - which is that last part that this issue was waiting for.
Please take a look to see if it looks OK - then close this issue if you think we are in good shape.

Thanks
Henry

**Comment by henry2cox** [comment]
I believe the problem has been fixed.
Thus, I am closing the issue now.

If there is still a problem, please reopen this issue or file a new one.  Please include a detailed description of the problem and, if possible, include a testcase that exhibits the issue.

Henry
