### ISSUE TITLE
latest version on sourceforge (1.14) is older/lower than the latest on github (1.16)

### ISSUE THREAD

**Issue by abazaba855** [linux-test-project/lcov#182]
Hi,

The latest version of lcov on sourceforge [1] (1.14) is older/lower than the latest on github [2] (1.16).

I'm not sure this is what was intended ;)

[1]
https://ltp.sourceforge.net/coverage/lcov.php
[2]
https://github.com/linux-test-project/lcov/releases

**Comment by henry2cox** [comment]
I'm not quite sure what to do about that.
Is there a way to simply note that the project has moved to this location (github), and that the old location is no longer supported or updated?  Or does somebody want commit to being in charge of keeping sourceforge up-to-date?  (I do not.)
Henry

**Comment by xaizek** [comment]
The [main page there](https://ltp.sourceforge.net/) already says:

> Moved to GitHub
>
> Project pages and wiki has been moved to GitHub

But if you open one of the pages, there is no notice that the site has moved, so not everybody will notice it.

**Comment by henry2cox** [comment]
It looks like the top-level lcov page on sourceforge (link [1], above) doesn't say that the project has moved.
I think it is probably sufficient to make a note there - especially at the head of the "Download" section - to note that 1.14 is available from sourceforge, but people should go to the github link for newer stuff.
Might also be useful to mention the date when that occurred (so people know that they are looking at a download that is at least a few years out-of-date).
I don't have permission to make that change, though.  Not sure who does.  Maybe Peter?

**Comment by mhoes** [comment]
I guess that updating the sourceforge page to have it (*clearly*) state that the project has moved on to github (and including the date that happened) would indeed be enough. Of course, as already stated, you would need someone who has write access to that sourceforge page in order to do so.

For what it's worth: my Fedora 37 vm still has lcov 14 (lcov-1.14-8.fc37.noarch) as the latest version in it's official repository, so I assume that at least the person that maintains that package for Fedora has indeed not noticed that the project has moved to another location.

**Comment by mhoes** [comment]
> The [main page there](https://ltp.sourceforge.net/) already says:
> 
> > Moved to GitHub
> > Project pages and wiki has been moved to GitHub
> 
> But if you open URL to one of the pages, there is no notice that the site has moved, so not everybody will notice it.

Ah. People may have simply bookmarked the 'download' page, and then never notice it as they never visit that page.

**Comment by xaizek** [comment]
I think using a sticky element like [described here](https://www.w3schools.com/howto/howto_css_sticky_element.asp) in the header of a page (which is probably already shared among all pages) will be a good solution as it's hard to ignore even if you open the page at some anchor.

**Comment by mhoes** [comment]
> I think using a sticky element like [described here](https://www.w3schools.com/howto/howto_css_sticky_element.asp) in the header of a page (which is probably already shared among all pages) will be a good solution as it's hard to ignore even if you open the page at some anchor.

Yes, that sounds like a perfect idea; the only thing left would be to find something that has write access to those pages ?

**Comment by GitMensch** [comment]
There is an "official" "moved to.." option with SF, but it isn't active for the LTP, to set this: login as project admin, go to https://sourceforge.net/p/ltp/admin/overview then to "Metadata" and then set "project moved to: https://github.com/linux-test-project" (some people also adjust the project title like "[moved to GitHub]").
The "moved to" clickable badge is visible on all SF pages for the project, just like the project title.

Another option would be to let SF sync from GitHub (one time setup as SF project admin): https://sourceforge.net/p/import_project/github / https://sourceforge.net/p/forge/documentation/GitHub%20Importer/#importing-to-an-existing-sourceforge-project.

**Comment by oberpar** [comment]
I have write access to the sourceforge LCOV HTML pages - I'll see that a notice is added as discussed here.

**Comment by oberpar** [comment]
This won't win me a web-design prize, but it is done:
https://ltp.sourceforge.net/coverage/lcov.php

**Comment by GitMensch** [comment]
Looks good to me - so while you have HTML pages write access you can't access https://sourceforge.net/p/ltp/admin/overview, right? If that's the case: is someone available? If not we can ask the SF staff to do this setting - I volunteer.

**Comment by oberpar** [comment]
Now I also set the "project moved" meta-data field for the LTP project, though of course it points to the LTP project page on github of which lcov is a child repository.
