### ISSUE TITLE
Support for MacOS needed to be improved

### ISSUE THREAD

**Issue by Lw-Cui** [linux-test-project/lcov#19]
I believe `lcov` uses gcc version to decide what kind of files to be scanned, but in MacOS the alias of `gcc` is `clang`, which causes `lcov` expects _.da_ instead of _.gcda_. But the default type of files created by `clang`  is _.gcda_. So I think it needed to be improved.

**Comment by oberpar** [comment]
Could you check if the issue you are referring to has been fixed with commit d7cc7591b3a7cc1ec95371d04e4fc46f10b3fd54? If not, please provide the full output of gcov --version.

**Comment by Lw-Cui** [comment]
Yeah it works!
BTW, the command `install` in my MacOS 10.12.1 doesn't have argument `-D`. I `make install` lcov successfully after deleting `-D`.

**Comment by jpfeuffer** [comment]
Glad I found this. I had exactly the same problems on MacOS 10.12.1.
Regarding the installation: Both the BSD install and the GNU install have a "-d" option, though. It creates the directories but does not copy the files yet. Maybe one could use that in addition to make the installation compatible on both platforms.

**Comment by oberpar** [comment]
Both issues should be fixed with current git HEAD.
