### ISSUE TITLE
lcov really slow due to JSON::PP

### ISSUE THREAD

**Issue by alkino** [linux-test-project/lcov#193]
My `lcov` was really, really slow.
I dig a bit, and found that the culprit was `decode_json()`.
I dig a bit more, find this: https://github.com/linux-test-project/lcov/blob/f1c1f9d5ea8cfb8622a6704d266decf8c88b8129/lib/lcovutil.pm#L1343-L1347

So I install `JSON::XS` and now this is fast again.

Should we print an info line if a fast JSON parser is not found?

**Comment by henry2cox** [comment]
update is in 0dc904e330ef
