### ISSUE TITLE
Automatically use `SOURCE_DATE_EPOCH`

### ISSUE THREAD

**Issue by Pesa** [linux-test-project/lcov#197]
It would be great if LCOV could default to `SOURCE_DATE_EPOCH`, if defined in the environment, for the timestamp used in the generated reports. In particular, I'm referring to the "Date" field in the HTML output, but this suggestion applies to any other timestamp used elsewhere in artifacts generated by LCOV.

See https://reproducible-builds.org/docs/source-date-epoch/ for more info.

**Comment by henry2cox** [comment]
Good suggestion.
It seems that the implementation already does this
  -  it already listens to env. variable SOURCE_DATE_EPOCH - see 'get_date_string' near line genhtml:6254.
  This is used for the 'current' date banner, unless some other value is passed as an argument.

- if this isn't working - can you describe a small example which illustrates the bug?

The place where this doesn't currently happen is in 'SourceFile::computeAge' near line genhtml:4016.
 - Arguably, that should use SOURCE_DATE_EPOCH i(if set) nstead of 'now()' to decide which age bucket the file belongs.
 - The only issue here is that the actual modify date of the file (say, coming from the file system or from the revision control system) might be more recent than SOURC_DATE_EPOCH - so the file age would be negative.
I can either treat that as zero - or emit an error (ignorable) and treat as zero.

The upshot:  I think the code already does what you want - unless you happen to be using date/owner binning.
(And if you _are_ using date/owner binning:  congratulations!  I'm now very curious about your application.)

**Comment by Pesa** [comment]
Apologies, I actually haven't tried to use it yet... I only grepped the sources before opening this issue, but I must have fat-fingered the command because it didn't return any results. I do see the variable being used in genhtml now. So please ignore me and sorry for the noise.

I don't use date binning so I can't really comment on that. I guess treating a negative value as zero makes sense. But I don't think this case should normally happen if you're doing fully reproducible builds.

**Comment by henry2cox** [comment]
Change seems to pass our regression tests...see cdde0d68ec6a.
I think this issue can be closed.  (I prefer the original author to close things as they may or may not agree that the original problem is addressed or not.)
Thanks for finding the issue - or for causing me to go review where else it might have an effect.
Henry

**Comment by Pesa** [comment]
Excellent, thanks a lot!
