### ISSUE TITLE
RPM cannot be installed on CentOS 7

### ISSUE THREAD

**Issue by s-martin** [linux-test-project/lcov#20]
When I try to install the current 1.12 RPM package on CentOS 7.2 with `sudo yum --nogpgcheck localinstall lcov-1.12-1.noarch.rpm` I get the error  `file /usr/bin from install of lcov-1.12-1.noarch conflicts with file from package filesystem-3.2-20.el7.x86_64`.

Apparently this is due to an incorrect package definition, where system directories are "owned" by lcov (see e.g. http://unix.stackexchange.com/a/257150).

Please provide an updated RPM package for download.

**Comment by s-martin** [comment]
Apparently this is already fixed in https://github.com/linux-test-project/lcov/commit/68320d932c5ee5537ae1c287fe52603ae2fecf8c.

So please provide just an updated RPM package for download. Thanks

**Comment by oberpar** [comment]
I'm somewhat reluctant to provide an updated 1.12 RPM - I'd rather invest the effort into putting out a new release with all changes since 1.12, including the fix for this problem. I'll try to go that route. Could you ping me in 2 weeks if there has been no progress on this matter?

**Comment by s-martin** [comment]
@oberpar OK

**Comment by oberpar** [comment]
Should be fixed with release v1.13.
