### ISSUE TITLE
branch coverage is not effect

### ISSUE THREAD

**Issue by yi452873250** [linux-test-project/lcov#204]
ubuntu 20.04 lcov 1.16
example demo：

#include <cstdio>
#include <cstring>
#include <iostream>
#include <string>

int main(int argc, const char *argv[])
{
    bool b = false;
    if (strcmp(argv[1], "1") == 0)
        b = true;

    char *a = nullptr;
    if (b)
      printf("Hai\n");
    delete[] a;

    std::string str("asdads");
    str = "cd";

    std::cout << str << std::endl;
    return 0;
}

steps:
1.edit lcovrc
line 100 
![image](https://user-images.githubusercontent.com/20902016/229048451-641083e3-a5da-48d3-87c5-23e67627b0a2.png)
line 193
![image](https://user-images.githubusercontent.com/20902016/229048534-cfb226bb-9d9b-470a-af65-296f08fab428.png)
2.build
![image](https://user-images.githubusercontent.com/20902016/229049322-70d2682e-c5bc-43a3-8b29-a45977bcd1b5.png)
![image](https://user-images.githubusercontent.com/20902016/229049417-71a5585e-51a5-4783-a514-43212b0fffc6.png)
build out foo foo.gcno
run ./foo 1
![image](https://user-images.githubusercontent.com/20902016/229049561-55a3ba10-1b5f-441c-a4c8-055db6a72239.png)
run lcov --capture --directory . --output-file foo.info --no-external
![image](https://user-images.githubusercontent.com/20902016/229049969-200cea84-e944-4d35-be16-76ec6fde1cd5.png)

run genhtml foo.info --output-directory output --title "basic test" --show-details --legend
![image](https://user-images.githubusercontent.com/20902016/229050359-61f14a32-3551-4be7-9419-1d724da01b51.png)

but the result is as fllow
![image](https://user-images.githubusercontent.com/20902016/229050644-81c6688d-baef-480e-ae27-a5d61632d64b.png)

what`s wrong with me ~~

**Comment by yi452873250** [comment]
![image](https://user-images.githubusercontent.com/20902016/229060839-39537535-8cb8-42be-bf23-83deb40a110c.png)

build this github demo ，but change c to cpp ，and insert some code，finally make

![image](https://user-images.githubusercontent.com/20902016/229057166-863fc05d-02f8-479e-9431-0a93867fe245.png)

I guess icov is only support c not c++

**Comment by henry2cox** [comment]
My guess would be that lcov/genhtml did not pick up the lcovrc that you edited.
The lcov version you will find at top-of-tree (TOT) has some features to help debug this - but 1.16 does not.

One thing to try is to change your LCOV command to

 `lcov --rc lcov_branch_coverage=1 ...`

and your genhtml command to

 `genhtml --branch-coverage ....`

and see what happens (if anything).  If this works - then the issue is that your lcovrc is not where you thought it was.  If it doesn't work..I'm not quite sure why not.  I suggest to download the latest code here - then change your capture command to add some verbosity and debug logging: `lcov --capture -v -v --debug ...` and then we can see what is happening.

The other question is what version of gcc you are using (`gcc -dumpversion`) - but that is unlikely to be your problem - unless your gcc is very, very old.

To the best of my knowledge:  lcov supports multiple languages, including C/C++/python and a few others :-)

Henry

NOTE: `...` means "use the rest of your original command line, unchanged"

**Comment by yi452873250** [comment]
> My guess would be that lcov/genhtml did not pick up the lcovrc that you edited. The lcov version you will find at top-of-tree (TOT) has some features to help debug this - but 1.16 does not.
> 
> One thing to try is to change your LCOV command to
> 
> `lcov --rc lcov_branch_coverage=1 ...`
> 
> and your genhtml command to
> 
> `genhtml --branch-coverage ....`
> 
> and see what happens (if anything). If this works - then the issue is that your lcovrc is not where you thought it was. If it doesn't work..I'm not quite sure why not. I suggest to download the latest code here - then change your capture command to add some verbosity and debug logging: `lcov --capture -v -v --debug ...` and then we can see what is happening.
> 
> The other question is what version of gcc you are using (`gcc -dumpversion`) - but that is unlikely to be your problem - unless your gcc is very, very old.
> 
> To the best of my knowledge: lcov supports multiple languages, including C/C++/python and a few others :-)
> 
> Henry
> 
> NOTE: `...` means "use the rest of your original command line, unchanged"

![image](https://user-images.githubusercontent.com/20902016/229396632-fbcfda86-5b2d-43fd-8006-baa0ff279160.png)
![image](https://user-images.githubusercontent.com/20902016/229396732-484c7e71-2211-44b9-8d20-16bac4216bec.png)

it doesn`t work ,has any idea?

**Comment by henry2cox** [comment]
Sorry.  I think I misread your original issue.
Please clarify.  I now think that you are complaining the lcov has picked up a bunch of branches which are related to exception handling in C++ - and you do not what to see those.
If that is the case:  please take a look at the `--filter branch` option (on TOT code version) and/or `lcov --capture --rc geninfo_no_exception_branch=1 ...`

If your issue is something different...could you explain what you wanted the result to be.  I'm having a hard time to guess from context.

**Comment by yi452873250** [comment]
> Sorry. I think I misread your original issue. Please clarify. I now think that you are complaining the lcov has picked up a bunch of branches which are related to exception handling in C++ - and you do not what to see those. If that is the case: please take a look at the `--filter branch` option (on TOT code version) and/or `lcov --capture --rc geninfo_no_exception_branch=1 ...`
> 
> If your issue is something different...could you explain what you wanted the result to be. I'm having a hard time to guess from context.

insert the option 
![image](https://user-images.githubusercontent.com/20902016/229670685-1fbe9393-9ccd-4795-8f8b-4dc390a458d1.png)

other operate is same with before

now result ,you see
![image](https://user-images.githubusercontent.com/20902016/229670754-3e39e77f-243a-42f3-a614-e3ed51008b4f.png)


I finally want the result is the branch coverage is correct ，but you see "printf" and "delete" and "cout" ,it shouldn`t show "+ -"
could you operate the branch coverage from top code demo~ thanks your reply

**Comment by henry2cox** [comment]
It appears that your compiler does not correctly mark the exception branches on lines 14, 15, 17, 18, and 20.
It notes that there are branches there - but does not mark that they are associated with exceptions.  As a result, 'gcov' (also part of your compiler tool chain) doesn't report exception branches there - and lcov produces the report you see.
This is not a surprising result.  AFAIK:  every version of gcc and every version of LLVM that I have tried, has at least a few of these issues.

I guess you already compared the reports that you get when you add or remvoe the "no_exception_branch" configuration flag - so you can deduce which branches are marked as exceptions and which are not.

At this point, you have 4 options:
  - compile your code to exclude exceptions.  The compiler won't put them in the code - and gcov/lcov won't be confused.  Your actual application may or may not require exception handling - so this may not be a viable solution for you.  (It does not work for us, for example.)
  - exclude branch coverage for this file/for these files where you don't like the reports.  This may be all files in your project - and so might not be a viable solution.
  - Use the `--filter branch` option described in the man pages (TOT).  This is a hack which basically looks for conditionals in the source lines which are claimed to contain branches - and then filters out branches which appear to be unrelated to any conditional.  There are a lot of limitations to this approach (see documentation/see other examples in some old issues in this github repo) - but it works fairly well in our environment.  YMMV.
  - live with funny reports.  You know what they mean - or can deduce what they mean - so maybe not a big deal.  Specifically:  if you are using a differential coverage methodology, then the bogus branches will appear in your 'signed off' category in the next build - allowing you to ignore code/tests that you have already reviewed, and focus on new/changed code.

Your other option is to take a look at the gcc/llvm implementation and improve the branch coverage implementation.  Then we all benefit.  (I caution that, if this was easy, it would have already been done.  Not a small project.)

I recognize that this is not a terribly satisfying answer.

Henry

**Comment by henry2cox** [comment]
Did you run again with `--filter branch` - and did that remove the exception branches you did not want to see?
As mentioned above:  the feature works for me (and for multiple other users).  If it is not working for you, then there is something unusual in your environment or you are using an old version of code.

If this is working correctly:  please close the issue.
If it is not working:  please clarify what is not working.

Thanks
Henry

**Comment by yi452873250** [comment]
on my computer ，it`s not work  . --filter branch is not command 
![image](https://user-images.githubusercontent.com/20902016/231326815-da1cbefd-ed52-4a2e-a782-323e01571973.png)

**Comment by henry2cox** [comment]
You need to be using the latest lcov source version from github.
Whatever old version you are using does not implement the various new features.
There is a link at the top of the main project page, to either clone the lcov repo or to download a zip file of the code.

To see which version you are currently using - and to verify that you are using the downloaded lcov - you can run `which genhtml` (will give you the install path) and `genhtml --version` (will tell you what install version genhtml thinks that it is).

**Comment by yi452873250** [comment]
![image](https://user-images.githubusercontent.com/20902016/231430017-27f4668a-a8ab-48d6-b5c5-943163fc4034.png)
I have downed this package
![image](https://user-images.githubusercontent.com/20902016/231430196-3f16d4a0-8657-4d24-a9a7-b8fa50041c1d.png)

then，run make make install
is it not correct？

**Comment by henry2cox** [comment]
You downloaded version 1.16.  It even told you that it is from june last year.  Not latest.

'Latest' is from the link at the top of the main page.
I appear not to be able to upload images - so I can't point you to it.
Look for the green button labeled `<> Code` - then either `Download ZIP` or `Clone`.

**Comment by yi452873250** [comment]
oh·I try it agin  ，my english is so bad ，so sometimes I dont get it，I m so sorry！

**Comment by henry2cox** [comment]
No worries.  Much (much!) better than my Mandarin. 
I'm lucky to make a successful coffee shop order.

**Comment by yi452873250** [comment]
now，I download the latest code  and unzip lcov-master,then cd lcovmaster dir,then run make install
![image](https://user-images.githubusercontent.com/20902016/231953506-ea1c8c0b-72ea-41ad-aa60-375cf171f698.png)

but run genhtml  ,it has error!

**Comment by henry2cox** [comment]
Right.  You are missing required Perl modules.  That is what the Perl error is telling you.
You can find a list of modules that lcov wants in the README file (or in the README section of the main page from where you downloaded the zip file).
It also shows one method to install missing perl modules - but your platform may have some other method.

"DateTime" is not likely to be the only module you don't have.

**Comment by yi452873250** [comment]
![image](https://user-images.githubusercontent.com/20902016/233006898-653d2663-77f5-431d-9f2b-26ee6b4c7061.png)
finally，it works，let me feel happy ，without your assistance，I cant do it  
Thank you for your patient answer
![image](https://user-images.githubusercontent.com/20902016/233007483-92012aca-7ad2-4567-9996-17cfdbb699ac.png)
