### ISSUE TITLE
Latest binary release broken on OSX Sierra, XCode8

### ISSUE THREAD

**Issue by chadbrewbaker** [linux-test-project/lcov#21]
Need a point release so homebrew can pull the fix for XCode8.

**Comment by oberpar** [comment]
The latest lcov release is v1.13. This release includes commit d7cc7591b3a7cc1ec95371d04e4fc46f10b3fd54 which appears to be Xcode8 related. There has been no fix committed after that, so I'm not sure what "fix for XCode8" refers to.

**Comment by chadbrewbaker** [comment]
Should clarify. Someone needs to host a binary build of 1.13 for OSX Sierra. I need to look into how homebrew binaries are usually hosted.

**Comment by oberpar** [comment]
This should be resolved with the latest release v1.14 - closing.
