### ISSUE TITLE
'make install' broken on at least MacOS

### ISSUE THREAD

**Issue by jkleppinger** [linux-test-project/lcov#211]
Since this commit:  https://github.com/linux-test-project/lcov/commit/c85695e3db6dd4f602b15be302d60184e6196488

> lcov % make PREFIX=./build V=1 install
install -d -m 755 ./build/bin
for b in lcov genhtml geninfo genpng gendesc ; do \
                 \
                install bin/$b ./build/bin/$b -m 755 ; \
                /Users/admin/Desktop/lcov/bin/fix.pl --version 1.16 --release 90.gcc551ec \
                       --libdir ./build/lib/lcov --bindir ./build/bin \
                       --fixinterp --fixver --fixlibdir --fixbindir \
                       --exec ./build/bin/$b ; \
        done
**usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2**
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Error: cannot stat ./build/bin/lcov: No such file or directory
**usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2**
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Error: cannot stat ./build/bin/genhtml: No such file or directory
**usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2**
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Error: cannot stat ./build/bin/geninfo: No such file or directory
**usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2**
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Error: cannot stat ./build/bin/genpng: No such file or directory
**usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2**
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Error: cannot stat ./build/bin/gendesc: No such file or directory
make: *** [install] Error 2

install utility on MacOS requires the "-m mode" argument to be BEFORE the file1 file2 arguments.

Lines like this in Makefile should have arguments re-ordered:
` $(INSTALL) bin/$$b $(DESTDIR)$(BIN_DIR)/$$b -m 755 ; \`

Not sure if there are other issues related to this commit, or what other operating systems might have the same error...

**Comment by jkleppinger** [comment]
Yes, this works fine in our build environment with the re-ordered args in Makefile.

**Comment by henry2cox** [comment]
Excellent.  This should be easy and quick to fix.

Are you using any of the other newer features in your environment - annotatation, version, and criteria callbacks, in particular?  Those are the ones that I think _might_ fail.  I think that most or all of the other features are pretty generic/OS agnostic.

**Comment by henry2cox** [comment]
should be fixed in 6838f80449
Please take a look

**Comment by jkleppinger** [comment]
Works great!  Thank you so much for the quick response and action!

I don't think we're using any newer features.

**Comment by henry2cox** [comment]
The README describes a bunch of them (briefly) if you want to take a look.
"Parallel execution" is another feature that may be problematic on mac (or may work perfectly - I don't know).
If your project is not tiny and your server is reasonable - then we observe near linear speedup up to about 20 cores (not as much after that).  YMMV.

Since you mentioned that your bug is fixed, I will close this issue.
