### ISSUE TITLE
branch coverage is incorrect in manual

### ISSUE THREAD

**Issue by jakeleventhal** [linux-test-project/lcov#212]
The man that shows all commands seems to indicate (correctly) that [branch coverage is disabled by default](https://github.com/linux-test-project/lcov/blob/e9d36782c1a71b7cb0d93715788271984db5f9a6/man/genhtml.1#L68-L69).

However, the detailed docs show that it is [enabled by default](https://github.com/linux-test-project/lcov/blob/e9d36782c1a71b7cb0d93715788271984db5f9a6/man/genhtml.1#L1220)

**Comment by henry2cox** [comment]
associated PR #213 merged.
Closing issue.
