### ISSUE TITLE
[genhtml] [Flutter] Directory paths doubled on report page

### ISSUE THREAD

**Issue by PiotrMag** [linux-test-project/lcov#230]
Hello there.
### While developing an application in Flutter, I came across a particular problem. **All directories have doubled paths on the HTML site created by the `genhtml` command**. I have created a simplified Flutter project to show what I mean. At the end of this post I have attached a **configuration info** that also has the mentioned problem. Below is the report page created for the simplified Flutter project.

<img width="715" alt="" src="https://github.com/linux-test-project/lcov/assets/19173949/e4884592-6312-4cab-916d-c7f1b80e31ee">

## Flutter project

To present the problem I have created a very simple Flutter project with the `flutter create <project_name>` command. I have added 2 simple classes to the project and 2 tests.

![](https://github.com/linux-test-project/lcov/assets/19173949/369d0a07-6105-4295-8566-1d5a6d6f8ce8)

Note that the structure of my project does not contain doubled directories (e.g., no "lib/src/lib/src" directory)

Below is the code of the classes I have added to the project.

`lib/src/sample_class.dart`
```dart
class SampleClass {
  int addNumbers(int a, int b) {
    return a + b;
  }
}
```

`lib/other_class.dart`
```dart
class OtherClass {
  int subtract(int a, int b) {
    return a - b;
  }
}
```

Here are the tests.

`lib/test/other_class_test.dart`
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:lcov_test/other_class.dart';

void main() {
  group('other class test', () {
    test('should subtract numbers', () {
      expect(OtherClass().subtract(5, 10), -5);
    });
  });
}
```

`lib/test/sample_class_test.dart`
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:lcov_test/src/sample_class.dart';

void main() {
  group('sample class tests', () {
    test('should add numbers', () {
      expect(SampleClass().addNumbers(2, 5), 7);
    });
  });
}
```

## The `lcov.info` file

I create `lcov.info` file in the `coverage` directory by running the `flutter test --coverage` command from the root directory of my project.

This is the content of the `lcov.info` file created by the `flutter test --coverage` command:
```lcov
SF:lib/other_class.dart
DA:2,1
DA:3,1
LF:2
LH:2
end_of_record
SF:lib/src/sample_class.dart
DA:2,1
DA:3,1
LF:2
LH:2
end_of_record
```

## Creating the coverage report with the `genhtml` command

Next, I run the `genhtml coverage/lcov.info -o coverage/html` command. The `coverage/html` directory gets created. The problem I can see is that the directories inside the `coverage/html` directory are doubled (see image below):
![](https://github.com/linux-test-project/lcov/assets/19173949/10a8f800-f30f-4bbd-a9be-f810fbbc70bb)

When I open the `coverage/html/index.html` file I can see that every directory has doubled path:
<img width="423" alt="" src="https://github.com/linux-test-project/lcov/assets/19173949/d30099af-0414-41fc-a07d-dc93e9e676d1">

## My investigation
I looked through the `genhtml` command's source code to see what might be causing the path doubling. 

> Note that I do not work with the Perl language so I might confuse some stuff about the code I am about to comment on

I came to the part of code in the `package GenHtml` `sub new` subroutine (on my machine it is around the 4450th line of code). The part of code is:
```perl
my $traceInfo = $current_data->data($f);
my $filename  = ReadCurrentSource::resolve_path($traceInfo->filename());
my ($vol, $parentDir, $file) = File::Spec->splitpath($filename);
if (!File::Spec->file_name_is_absolute($filename)) {
    if ($parentDir) {
        $parentDir = File::Spec->catfile($main::cwd, $parentDir);
    } else {
        $parentDir = $main::cwd;
    }
    $filename = File::Spec->catfile($parentDir, $filename);
}
```
I have added `print($filename)`s before and after the if block. The code looks like this:
```perl
my $filename  = ReadCurrentSource::resolve_path($traceInfo->filename());
print("before if block: ");
print($filename);
print("\n");
my ($vol, $parentDir, $file) = File::Spec->splitpath($filename);
if (!File::Spec->file_name_is_absolute($filename)) {
    if ($parentDir) {
        $parentDir = File::Spec->catfile($main::cwd, $parentDir);
    } else {
        $parentDir = $main::cwd;
    }
    $filename = File::Spec->catfile($parentDir, $filename);
}
print("after if block: ");
print($filename);
print("\n");
```
 And indeed the path is doubled after the `if` block (as can be seen in the output of the `genhtml` command):
![](https://github.com/linux-test-project/lcov/assets/19173949/8786b729-3ca2-4bdb-bcc0-d67be96c5a71)

I would like to address the `$filename = File::Spec->catfile($parentDir, $filename);` line. When I change it to `$filename = File::Spec->catfile($parentDir, $file);` the `genhtml` commands starts working as I would expect (the directories on the report page no longer have doubled paths)
<img width="334" alt="" src="https://github.com/linux-test-project/lcov/assets/19173949/24ea65d7-4e3a-4a16-a1f7-0c7d7d726701">

Am I not running the `genhtml` command correctly or is there a mistake in the `genhtml` script?

As of 3 august 2023 I can see that the `genhtml` script in the `lcov/bin` directory here on Github also has the "problematic" line of code. https://github.com/linux-test-project/lcov/blob/2694692d420fa258cc32c574dccd7e3943d3a910/bin/genhtml#L4594

## Configuration info:
Lcov:
> lcov: LCOV version 2.0-1 (installed via Homebrew)

Flutter:
> Flutter 3.10.6 - channel stable

Dart:
> Dart 3.0.6
---
Regards,
Peter

**Comment by henry2cox** [comment]
Oops.
I will look at the history of this particular change to see what I was thinking (or, apparently, not thinking).
I suspect that you are right - and this is a bug.
I may have made a similar mistake elsewhere in the code - so need to check that too.

(As Bob Lund - my old shop teacher - used to say:  he who makes no mistakes, makes nothing at all.)
Thanks for the bug report.

Henry

**Comment by henry2cox** [comment]
Fixed in 02ece21d54 
Please give it a try and either close this issue (if bug is fixed) or describe the ongoing breakage.

(Aside from this commit, I pushed a few other pending changes that you may or may not want to ignore.)

Henry

**Comment by PiotrMag** [comment]
I have installed the latest version `02ece21` of `lcov` from Github (cloned git repository and installed with `make`). I tested the `genhtml` command with a different Flutter project that also had the same issue with doubled paths in the report. It works as expected (directories in the report no longer have doubled paths). Thank you for the quick response.

**I confirm that the fix `02ece21` works**

**Are there any plans to release a new stable version of `lcov`?**

Regards,
Peter

**Comment by henry2cox** [comment]
> Are there any plans to release a new stable version of lcov?

I'll let Peter comment on that.
Glad that the fix worked (though, in truth, it is your fix).

**Comment by agetman-kw** [comment]
hey @henry2cox , do you plan to release this fix? 😅
it's been a while sine you've fixed that 😄

**Comment by henry2cox** [comment]
Hi -
It turns out that I don't actually know what the procedure to create a release looks like ;-(
Thus - I'm probably not competent to do it.  Or maybe somebody can point to a recipe?

Typically, though:  Peter has taken care of it.  I haven't seen him around in quite a long time, though - so maybe we do have to figure this out.  Open to suggestions.
Henry

**Comment by henry2cox** [comment]
I think I figured it out :-)
Need to go through a few hoops with my company in order to make/upload a release - so it may take a while.
Also - it is not unlikely that my first attempt is broken in some way that I fail to detect.

**Comment by agetman-kw** [comment]
@henry2cox thanks for quick reply :) Waiting for new release 🙏

**Comment by henry2cox** [comment]
I just attempted to create a release - marked a 'v2.1-beta'.
I am not entirely sure that I did this correctly.
Could you take a look and let me know what you find.  Does it appear to work?  Are there issues that you see?

Presuming that it all looks OK - or that we figure out and fix whatever I did wrong, then I will aim for an actual 2.1 release in a couple of weeks/after things seem to settle a bit.
