### ISSUE TITLE
Docs/Makefile mismatch for local installations

### ISSUE THREAD

**Issue by billschereriii** [linux-test-project/lcov#239]
There is a discrepancy between the project documentation (README.md) and the Makefile when it comes to performing a local installation. Where the docs suggest that one uses the PREFIX make variable to define a target directory, the Makefile, in the `info` target, points people to the `DESTDIR` make variable.

From what I can see (though I admit I didn't look too closely), either one will work. I assume both are supported to maintain backward compatibility.

**Comment by henry2cox** [comment]
Yeah - I noticed the redundant DESTDIR variable when I was adding code to check for absolute vs relative path.
(I removed it - so now we use only PREFIX.)

I'll push the fix fairly shortly (along with a couple of other fixes and enhancements.)

**Comment by henry2cox** [comment]
Fixed in c9b83cf69681b5bca46bde213d2c8e2196395349

**Comment by henry2cox** [comment]
Closing this now.
I think it was fixed some time back.
Henry
