### ISSUE TITLE
geninfo can't continue on find errors

### ISSUE THREAD

**Issue by abussy-aldebaran** [linux-test-project/lcov#241]
I got the error:

`geninfo: ERROR: Error return code from 'find "myDir" ...':`

When I run `find . -name "*.gcno"`, all the `.gcno` paths are returned, there is just one `Permission denied` in the middle, which I'm ok to ignore. But `find` returns a non-zero exit code, which causes the error in `geninfo`. Would it be possible to ignore such errors from `find` ?

**Comment by henry2cox** [comment]
yeah - possible.
Right now, we call `die`.  Straightforward to turn that into an 'ignorable_error' (but then a bit painful to write the regression test to prove that the feature works).
Will add to the list.

**Comment by abussy-aldebaran** [comment]
I understand. I've been able to write a small reproducible scenario in bash if it can help you.
```
mkdir test
chmod -r test
lcov --capture --directory .
```

**Comment by henry2cox** [comment]
fixed in 0653f1e717c - pushed this morning.
Please go ahead and close this issue if the fix seems sufficient.
Thanks
