### ISSUE TITLE
Error when installing from homebrew

### ISSUE THREAD

**Issue by chris-wickens** [linux-test-project/lcov#256]
My CI build just started getting an error when running `brew install --HEAD lcov` which I imagine relates to the batch of commits pushed to master about an hour ago.

Is it possible to get a release of the last few months' changes so we can have a stable version to install via homebrew? Specifically I need this commit: https://github.com/linux-test-project/lcov/commit/23d166a1742e4e4d87449252cbac01cc39f5ef8a

Error details:
<details>
brew install --HEAD lcov
Running `brew update --auto-update`...
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:d783cbeb6e6ef0d71c0b442317b54554370decd6fac66bf2d4938c07a63f67be
######################################################################################################################################################################################################### 100.0%
==> Pouring portable-ruby-3.1.4.arm64_big_sur.bottle.tar.gz
==> Auto-updated Homebrew!
Updated 4 taps (dart-lang/dart, leoafarias/fvm, homebrew/core and homebrew/cask).
==> New Formulae
abi3audit                          dalfox                             leoafarias/fvm/fvm@3.0.0-beta.2    python-abseil                      python-pathspec                    shell2http
action-validator                   dcp                                leoafarias/fvm/fvm@3.0.0-beta.3    python-anytree                     python-pbr                         shellspec
ain                                der-ascii                          leoafarias/fvm/fvm@3.0.0-beta.4    python-argcomplete                 python-platformdirs                sigma-cli
ali                                dezoomify-rs                       leoafarias/fvm/fvm@3.0.0-beta.5    python-asn1crypto                  python-pluggy                      signmykey
amass                              dicebear                           libconfini                         python-attrs                       python-ply                         sigstore
ansible@8                          diffoci                            libcyaml                           python-boto3                       python-prompt-toolkit              skate
apkleaks                           direwolf                           libdicom                           python-botocore                    python-psutil                      sloth
appstream                          dockerfile-language-server         libdpp                             python-brotli                      python-regex                       smlfmt
argc                               dockly                             libjuice                           python-cachetools                  python-requests                    snakeviz
asitop                             doppler                            libnghttp3                         python-chardet                     python-requests-oauthlib           snyk-cli
auditwheel                         drogon                             libsail                            python-charset-normalizer          python-rich                        solo2-cli
authz0                             eatmemory                          mariadb@11.1                       python-cli-helpers                 python-s3transfer                  spglib
awscli-local                       faircamp                           mediamtx                           python-colorama                    python-setuptools                  spicetify-cli
badkeys                            favirecon                          memray                             python-configargparse              python-setuptools-scm              spidermonkey@91
bandicoot                          flyscrape                          mentat                             python-configobj                   python-sympy                       sqlfmt
bao                                frozen                             minder                             python-cycler                      python-termcolor                   squealer
bashunit                           gdrive@2                           modsurfer                          python-dateutil                    python-tk@3.12                     squiid
biodiff                            geoip2fast                         netlistsvg                         python-dicttoxml                   python-trove-classifiers           ssh-mitm
bkcrack                            ghc@9.4                            node@20                            python-distlib                     python-urllib3                     sshportal
bob                                ghc@9.6                            noir                               python-distro                      python-wcwidth                     tailspin
bomber                             git-mediate                        nvimpager                          python-docopt                      python-websocket-client            telegram-downloader
bounceback                         gitsign                            ocaml@4                            python-filelock                    python-xlsxwriter                  terraform-local
bozohttpd                          gittuf                             onionprobe                         python-gdbm@3.12                   python@3.12                        texttest
build2                             glbinding@2                        open-simh                          python-hatch-fancy-pypi-readme     qbittorrent-cli                    three-body
cargo-sweep                        goresym                            opentofu                           python-hatch-vcs                   rapidfuzz-cpp                      tlrc
cariddi                            gossip                             orbuculum                          python-hatchling                   raven                              trafilatura
certgraph                          gotpm                              orogene                            python-idna                        rdap                               uvicorn
certsync                           gptline                            osctrl-cli                         python-jinja                       redress                            vet
cf2tf                              graphqlviz                         oslo                               python-jmespath                    redwax-tool                        virtctl
cfripper                           haiti                              pan                                python-json5                       reflex                             vulsio-gost
chainloop-cli                      immer                              patat                              python-kiwisolver                  regclient                          whisper-cpp
chainsaw                           incus                              patch-package                      python-magic                       rekor-cli                          witness
changie                            instaloader                        pciutils                           python-mako                        retire                             wormhole-william
cherrybomb                         intercept                          pdfalyzer                          python-markdown-it-py              retry                              xeol
chisel-tunnel                      invoice                            pdfrip                             python-matplotlib                  richgo                             xnvme
cidr                               jprq                               perl-xml-parser                    python-mdurl                       ruler                              yatas
cliam                              jupyter-r                          php@8.2                            python-mpmath                      saf-cli                            zix
cloudsplaining                     karmadactl                         phylum-cli                         python-msgpack                     scarb                              zug
crunchy-cli                        kew                                pmix                               python-networkx                    scikit-image
csprecon                           lager                              presenterm                         python-oauthlib                    scilla
daktilo                            leoafarias/fvm/fvm@3.0.0-beta.1    pter                               python-openapi3                    scoutsuite
==> New Casks
affine                        codewhisperer                 fossa                         keymapp                       music-decoy                   paulxstretch                  telegram-a
amie                          commandpost                   free-podcast-transcription    kuaitie                       navigraph-charts              proton-drive                  timemachinestatus
anka-build-cloud-controller   deskpad                       garmin-basecamp               libndi                        navigraph-simlink             rode-central                  to-audio-converter
anka-build-cloud-registry     deveco-studio                 greenery                      low-profile                   notes-better                  routine                       truhu
batchoutput-pdf               devtunnel                     gstreamer-development         macgpt                        nvs                           screens-assist                tunetag
bezel                         douyin-chat                   gstreamer-runtime             mdb-accdb-viewer              nx-studio                     senabluetoothdevicemanager    vimcal
brickstore                    dropbox-dash                  hapigo                        mediamate                     october                       sf                            wave
brightintosh                  ecodms-client                 hides                         metamer                       ok-json                       simplex                       wiso-steuer-2024
btp                           effect-house                  hoppscotch                    mindmac                       orka3                         songkong                      writerside
cardo-update                  finbar                        hp-easy-admin                 mitmproxy                     ovito                         space-capsule                 xliff-editor
clibor                        focusrite-control-2           jazz2-resurrection            modrinth                      ovito-pro                     spacedrive                    xsplit-vcam

You have 29 outdated formulae installed.

==> Fetching lcov
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/1d139cf5f4ec994431136edf5476135fa8a8d7cc/Formula/l/lcov.rb
######################################################################################################################################################################################################### 100.0%
==> Downloading https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/JSON-4.10.tar.gz
######################################################################################################################################################################################################### 100.0%
==> Downloading https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/PerlIO-gzip-0.20.tar.gz
######################################################################################################################################################################################################### 100.0%
==> Cloning https://github.com/linux-test-project/lcov.git
Cloning into '/Users/chriswickens/Library/Caches/Homebrew/lcov--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/lcov/HEAD-d97b0ee_1/libexec
==> make
==> make install
==> perl Makefile.PL INSTALL_BASE=/opt/homebrew/Cellar/lcov/HEAD-d97b0ee_1/libexec
==> make
==> make install
==> make PREFIX=/opt/homebrew/Cellar/lcov/HEAD-d97b0ee_1 BIN_DIR=/opt/homebrew/Cellar/lcov/HEAD-d97b0ee_1/bin MAN_DIR=/opt/homebrew/Cellar/lcov/HEAD-d97b0ee_1/share/man install
Last 15 lines from /Users/chriswickens/Library/Logs/Homebrew/lcov/07.make:
install: /lcov: Operation not permitted
Error: cannot stat /lcov: No such file or directory
  INSTALL /genhtml
install: /genhtml: Operation not permitted
Error: cannot stat /genhtml: No such file or directory
  INSTALL /geninfo
install: /geninfo: Operation not permitted
Error: cannot stat /geninfo: No such file or directory
  INSTALL /genpng
install: /genpng: Operation not permitted
Error: cannot stat /genpng: No such file or directory
  INSTALL /gendesc
install: /gendesc: Operation not permitted
Error: cannot stat /gendesc: No such file or directory
make: *** [install] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

lcov's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
</details>

**Comment by henry2cox** [comment]
Sorry about that.  Unsuccessfully juggling too much.
Ought to be fixed in 79e574b2bbf432

**Comment by henry2cox** [comment]
With respect to release:  will let Peter comment.
Henry

**Comment by chris-wickens** [comment]
That's fixed, thanks Henry.

**Comment by henry2cox** [comment]
As my high school shop teacher used to say: 
  He who makes no mistakes, makes nothing at all.

But sorry about the bug.

**Comment by henry2cox** [comment]
I'm going to go ahead and close this as I think the proximate issue is fixed.
If there is still a problem - please reopen this issue or file a new one.
If it all posible, please provide a testcase which illustrates the problem - e.g., the command line above helped a lot :-)
Thanks
