### ISSUE TITLE
Differential coverge numbers don't add up

### ISSUE THREAD

**Issue by Vladyyy** [linux-test-project/lcov#262]
See the examples provided below:
![image](https://github.com/linux-test-project/lcov/assets/51840210/8b797d82-b83b-41b7-8e82-437ad09a45d4)

I would expect that `UBC + CBC = Total` but that is not the case. In the example
243716 != 71615 + 171445 - > 243716 != 243060

Is my `UBC + CBC = Total ` assumption wrong ?

**Comment by henry2cox** [comment]
Total should be equal to the sum of all the (non-deleted) coverpoints:  UBC + CBC + LBC + + GBC + UIC + UNC + GNC +GIC
That is:  the sum of all the baseline coverpoints which still exist, plus all the new coverpoints created by newly added code as well as those created by changed compiler directives (say).

**Comment by Vladyyy** [comment]
Thanks, that makes sense. 

A follow-up question:
Does CBC / (CBC + UBC) * 100 represent the coverage percentage for the baseline

**Comment by Vladyyy** [comment]
Thanks, this was helpful.

>>his is discussed (to some degree) in the IEEE paper referred in the README - primarily in the section which talks about coverage criteria.

I did read the paper and watched you presentation
