### ISSUE TITLE
Path normalization normalizes foo/././bar incorrectly

### ISSUE THREAD

**Issue by jcranmer** [linux-test-project/lcov#27]
I was trying to figure out why my tool was giving different file lists from lcov on a very large codebase (mozilla-central, if you're wondering). Turns out that one of the .gcno files had source names like
/home/worker/workspace/build/src/modules/woff2/src/././buffer.h--gcov processed this into .../src/buffer.h, but geninfo wasn't finding that in the module, so it was dropping it from the buffer.

It looks like the normalization in solve_relative_path is to blame:
```perl
        # Remove .
        $result =~ s/\/\.\//\//g;
        $result =~ s/\/\.$/\//g;
```

**Comment by oberpar** [comment]
Sorry for the delay. This should be fixed by commit 3b378b0e76be95971680056d864d0e13f4a08557. Thanks for reporting the issue!
