### ISSUE TITLE
geninfo somehow forgets the line number of functions

### ISSUE THREAD

**Issue by jcranmer** [linux-test-project/lcov#28]
I'm not entirely sure why it's the case, but sometimes geninfo ends up failing to attach a line number to functions, so the output gets FNDA: lines but no corresponding FN: lines.

I've attached a minimized pair of gcda/gcno files to this bug to illustrate the situation.

[gcda_pair.zip](https://github.com/linux-test-project/lcov/files/966602/gcda_pair.zip)

**Comment by oberpar** [comment]
This should be fixed with commit 29814f18ec207ebaefa7b41f6e5acc4eca6d7a7a. Thanks for reporting this issue!
