### ISSUE TITLE
genhtml: --keep-going doesn't work for ERROR: <file> is not readable or doesn't exist.

### ISSUE THREAD

**Issue by ntnx-aleksa** [linux-test-project/lcov#285]
Hello,
we're facing an error handling issue in genhtml after we switched to lcov 2.0.

genhtml version
```
$ genhtml --version
genhtml: LCOV version 2.0-1
```

Command:
```
genhtml --demangle-cpp --keep-going --rc genhtml_hi_limit=80 --rc genhtml_med_limit=40 ./coverage_merged.info
...
genhtml: ERROR: <path> is not readable or doesn't exist. See the '--substitute' and '--synthesize-missing' genhtml options for methods to fix the missing path or ignore the problem.
```

Why isn't this error ignorable using `--ignore-errors source` or `--keep-going`? The man page clearly states:
> source: The source code file for a data set could not be found.

This seems like a breaking change compared to lcov 1.x.

**Comment by henry2cox** [comment]
If this was an ignorable error, what you want the tool to do when it can't find the source or the source is missing, and you also told it that you wanted it to generate the source code view?

What it _does_ do is to tell you that it can synthesize a "source" view for you, if you want.
Or you can exclude the file in question, or you can tell it where to find the actual code.

**Comment by ntnx-aleksa** [comment]
I'm aware of the possible solutions, however I disagree that this is not an ignorable error. The previous lcov versions simply did not include the source file in the HTML output and discarded the annotated counters. This is the behavior that should be present by default in genhtml, and `--synthesize-missing`, `--substitute` and `--resolve-script` should all be alternatives to this.

**Comment by henry2cox** [comment]
Sounds like you have a solution:  use the prior version.

The doc used to say _some errors are not ignorable_ - but it seems to no longer do so.
That's an issue that I will (eventually) fix.

**Comment by ntnx-aleksa** [comment]
I don't think this is a constructive answer to my issue. 
I've just provided a way to resolve this with reasonable behavior that was present before. 
Even in the [error message that you have written yourself ](https://github.com/linux-test-project/lcov/blame/master/bin/genhtml#L4840) you state that the problem could be ignored, and it obviously can.

**Comment by ntnx-aleksa** [comment]
I now better understand your concerts about the previous version's behavior - it doesn't make for a more accurate report.
I took some time to investigate the source of the missing files, and it seems to be a Python C wrapper whose artifact is an .so file that's referencing .c files that are actually temporary artifacts created from existing .py files. This is on Clang 13, gcov-compatible code coverage.

Thank you for considering to add the filter, it's useful for us in these situations where we need a report, even though it might not be the most accurate.

**Comment by henry2cox** [comment]
I believe this issue is fixed - and will go ahead and close it a few days from now if there are no further updates/nothing that needs to be done.

**Comment by henry2cox** [comment]
Closing this issue now.
If there is still a problem, please feel free to reopen this issue or file a new one.
Please describe the problem in detail and provide a testcase which illustrates the issue, if possible.
