### ISSUE TITLE
Duplicate folder structure (--prefix does not help)

### ISSUE THREAD

**Issue by bgintzairspace** [linux-test-project/lcov#294]
Hello,
I am newish to coverage reports, but I am getting a weird error that I can't seem to find answers about on stackoverflow.

I am generating a coverage report from a Flutter test and it looks like it creates the lcov.info file correctly, for example:

`SF:lib/src/features/authentication/domain/app_user.dart`

It also gets into the lcov_filtered.info file with the same information.  But once I use genhtml to create the HTML report it duplicates the full path, so the report for the above file lives in

`lib/src/features/authentication/domain/lib/src/features/authentication/domain`

And shows up in the HTML as:

![Screenshot 2024-05-21 at 11 43 54 AM](https://github.com/linux-test-project/lcov/assets/162149602/ce756bf1-0d2f-4e07-8497-17c6e1e4fc79)

I feel like I am missing something simple.  Any ideas?

**Comment by henry2cox** [comment]
This looks like bug #230.
Which lcov version are you using?
If updating to the 2.1 release and/or updating to current TOT do not resolve the issue:  please try to create a testcase which exhibits the problem.
Thanks
Henry

**Comment by bgintzairspace** [comment]
@henry2cox Thank you!  Upgrading fixed the issue!
