### ISSUE TITLE
gcov error：std::bad_alloc

### ISSUE THREAD

**Issue by Jeling-W** [linux-test-project/lcov#295]
I have used different versions of gcov and lcov to perform coverage analysis on two .cpp files. Both gcda and gcno files are generated correctly, and the file paths are accurate with no damage to the files. When generating the coverage of one file, it is normal, but when attempting to generate coverage for another file, I always encounter an error:

```
terminate called after throwing an instance of 'std::bad_alloc'  
        what(): std::bad_alloc
```
        
I have checked my system's memory, and it is sufficient. The file is not large

**Comment by Jeling-W** [comment]
When using gcov version 8.3.0 paired with lcov 1.13 or gcov 9.4.0 paired with lcov 2.0 to process main.cpp, an error is encountered:
```
terminate called after throwing an instance of 'std::bad_alloc'  
        what(): std::bad_alloc
```

When using gcov version 4.8.0 to process main.cpp, a different error is encountered:
`main.gcno no functions found`

After using gcov 4.8.0 to execute: `gcov main.cpp`, there will be some prompts for `main. cpp: no lines for`, but the main. cpp.gcov file can still be generated normally,

 using gcov8.3 or gcov9.4 to execute: `gcov main.cpp`, the error is encountered:
```
terminate called after throwing an instance of 'std::bad_alloc'  
        what(): std::bad_alloc
Aborted (core dumped)
```

The same compilation process and generation coverage process are fine in the func.cpp file

**Comment by henry2cox** [comment]
Current gcc version is 13.
gcc/4.8 is about 10 years old and 8.3 is more than 5.
I suggest to upgrade.

This isn't an lcov bug - but the same observation applies.  Current 'release' version is 2.1. lcov/1.13 predates move to github - and is really, really old.

**Comment by Jeling-W** [comment]
Is it possible that there is an error in the content of my gcda and gcno?

**Comment by henry2cox** [comment]
Anything is _possible_.
An error in the compile-time data (gcno) would be a compiler bug.
An error in the runtime data (gcda) would either be a compiler or C/C++ runtime bug.
Or this could be a bug in gcov.
If you really want to diagnose it:  then you will need to do some experiments - and probably need the source code for the toolchain components so you can see what they are doing.
Or you could upgrade and hope it goes away.
Or you could upgrade - discover that there is still an issue - and then debug more recent toolchain code.

Not sure your affiliation or interests - but if you happen to be a computer science or software engineering student somewhere, then this could be a really excellent learning experience:  track down a fix a real bug in a nontrivial framework.
I guarantee you that you would learn a _lot_.  (I guarantee you that I would learn a lot.)

**Comment by henry2cox** [comment]
Looks like gcov has a bug (or the compiler has a bug and is producing something that crashes gcov).
Crashes are always easier to debug than wrong results - so you case is somewhat lucky.

I seriously doubt that anyone is going to be able to identify or fix the issue without a testcase.
If you want to debug it yourself:  you might want to start by looking at the stack trace in your core dump.
Then you might want to build a debug version of gcov and run there to see what went wrong.

It is also probably worth trying your example with llvm to see if it fails with an entirely different toolchain.

The other thing you can do is suggested by the lcov error message above:  ignore the gcov error and generate data for the rest of your project.  This particular compilation unit won't have any data, but you might not care.

**Comment by henry2cox** [comment]
Closing this issue now.
There has been no update in some time - and the problem description seems like a gcc/gcov bug rather than an lcov issue.

If you think that there is still an lcov problem - please either reopen this issue or file a new one.
Please include a testcase which exhibits the problem.
Henry
