### ISSUE TITLE
lcov only works with gcc 4.6 and lower

### ISSUE THREAD

**Issue by spackard** [linux-test-project/lcov#3]
I noticed the latest release of lcov (1.11) only works with gcc 4.6 and lower.  With 4.7, 4.8, and 4.9, lcov immediately dies.  Are there any plans to update lcov to work with the latest gcc release (4.9.2 as of this posting)?

**Comment by oberpar** [comment]
I just successfully validated that lcov still works with GCC version 4.8.2. Could you post the error message you are seeing?

**Comment by spackard** [comment]
It turns out I was feeding lcov the wrong version of gcov to run with.  When I gave it the path to gcov from gcc 4.9.2, it worked just fine.  You can withdraw this.
