### ISSUE TITLE
RPM 2.1-1 does not install on Rocky Linux 8 or Centos7

### ISSUE THREAD

**Issue by Luke-LoPresti** [linux-test-project/lcov#301]
When attempting to install the lcov rpm using yum/dnf, it fails with the following error.

> yum install lcov-2.1-1.noarch.rpm

> ...
...
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Transaction test error:
  package lcov-2.1-1.noarch is intended for a different operating system

Tested on Rocky Linux 8 and Centos7.
The previous rpm lcov-2.0-1.noarch.rpm installs with no errors.

**Comment by henry2cox** [comment]
You may be able to get this to work, by using the `--ignoreos` RPM flag.  `man yum` indicates that there is no similar flag - and it is not clear whether you can pass additional RPM flags to yum, nor how to do it, if it is possible.

I confess to not knowing how this is encoded in the RPM - and did not even realize that this was an issue - but it does appear that there are some flags one can use while generating the RPM to make it more generic.  I'll experiment.

**Comment by henry2cox** [comment]
There is a 2.2-beta release available which should address the problem..
I'll close this issue in a couple of days if there are no further updates.

**Comment by henry2cox** [comment]
No updates - so I am closing this issue now.
If there is still a problem, please either reopen this issue or file a new one.
Please include a testcase which exhibits the problem and/or provide a detailed description of the problem you see.
