### ISSUE TITLE
Option geninfo_external from a user-provided lcovrc file gets ignored

### ISSUE THREAD

**Issue by cesaro** [linux-test-project/lcov#307]
If I read correctly the lcovrc(5) man page, doing this:
```sh
echo 'geninfo_external = 0' > rc
lcov -c -i -d path/to/src --config-file rc -o zero.info
```
and doing this:
```sh
lcov -c -i -d path/to/src --no-external -o zero.info
```
should produce exactly the same results, namely, generating a trace in `zero.info` that exclusively describes the coverpoints of C++ files recursively found in `path/to/src`.

However, only the second case (with `--no-external`) does what it promises. The first case (with `--config-file rc`) outputs a `zero.info` file such that `lcov -l zero.info` prints files outside `path/to/src`. What's more, in the first case, having an `rc` file with

- only the line `geninfo_external = 0`, or
- only the line `geninfo_external = 1`, or
- no lines at all (empty)

produces exactly the same results.

Version info: lcov v2.1, running on Red Hat Enterprise Linux 8.4, while analyzing .gcno files generated by gcc 9.3.0.

If you have trouble to reproduce, please ping me and I will provide detailed instructions.

**Comment by henry2cox** [comment]
Better to provide complete testcase - saves effort to reproduce.
Even better to create complete testcase in style of lcov regression suite, and corresponding PR.

**Comment by lozanopo** [comment]
[CE_DoC_FB15.pdf](https://github.com/user-attachments/files/16036677/CE_DoC_FB15.pdf)
[CE_DoC_FB14.pdf](https://github.com/user-attachments/files/16036678/CE_DoC_FB14.pdf)
[Fitbit_UK_DoC_FB421_Nov2021.pdf](https://github.com/user-attachments/files/16036679/Fitbit_UK_DoC_FB421_Nov2021.pdf)
[AWS_Event_Terms_and_Conditions_Spanish_2022_03_29 2.pdf](https://github.com/user-attachments/files/16036680/AWS_Event_Terms_and_Conditions_Spanish_2022_03_29.2.pdf)
[CE_DoC_FB202_Aria2_Updated_102020.pdf](https://github.com/user-attachments/files/16036681/CE_DoC_FB202_Aria2_Updated_102020.pdf)
[CE_DoC_FB16.pdf](https://github.com/user-attachments/files/16036682/CE_DoC_FB16.pdf)

**Comment by lozanopo** [comment]
Juanlozano😁

**Comment by henry2cox** [comment]
Not sure what to make of the attachments form @lozanopo.  Seems unrelated to lcov generally, and specifically unrelated to this issue.

(Issue is fixed the the commit mentioned above, BTW.)

**Comment by oberpar** [comment]
> Not sure what to make of the attachments form @lozanopo. Seems unrelated to lcov generally, and specifically unrelated to this issue.

Could be spam or malware related, so to stay on the safe side I deleted the comment from this issue.
