### ISSUE TITLE
genhtml failure with --no-function-coverage

### ISSUE THREAD

**Issue by gtyukasz** [linux-test-project/lcov#331]
Hello,

With version 2.2, genhtml fails with `ERROR: Can't use an undefined value as a HASH reference` if the `--no-function-coverage` option is used with lcov/genhtml.

I am not familiar with the code, but the issue seems to be that `$fileCovInfo->functionMap()` returns `undef` [here](https://github.com/linux-test-project/lcov/blob/b7ebec032b84d89b1bc6e200a764ec1a73bea144/bin/genhtml#L5114).

Best regards,
Gabor

**Comment by henry2cox** [comment]
Thanks for finding the bug.  Should be fixed in 401e15b33
(And I made a typo in the commit comment.)

**Comment by henry2cox** [comment]
Fixed - so closing this issue now.
If there is still a problem, please either reopen this issue or file a new one.  Please include a detailed description of the issue, and ideally, a small testcase which illustrates the bug.
