### ISSUE TITLE
[Git `HEAD`] `py2lcov` and tests: Python command `coverage` is named `python3-coverage` in Debian land (including Ubuntu)

### ISSUE THREAD

**Issue by hartwork** [linux-test-project/lcov#347]
Hi!

Multiple scripts in here call out to command `coverage`, e.g.:
- `bin/py2lcov`
- `tests/py2lcov/py2lcov.sh`

However Python command `coverage` [is named `python3-coverage` in Debian official packaging land](https://packages.debian.org/sid/amd64/python3-coverage/filelist) (including Ubuntu) and so the code base probably needs to do some auto-detection or allow specifying a custom command through an environment variable or command line argument. Thanks for your consideration.

Best, Sebastian

**Comment by hartwork** [comment]
@henry2cox should we close this as fixed by #353 ?

**Comment by henry2cox** [comment]
I think so.
Unless there is some better way - but this is adequate, if not beautiful.
