### ISSUE TITLE
[Git `HEAD`] `py2lcov` and `xml2lcov`: Use of `subprocess.run([..], shell=True, [..])` allows command injection

### ISSUE THREAD

**Issue by hartwork** [linux-test-project/lcov#350]
For example:

```console
# ./bin/py2lcov 'with spaces'
/bin/sh: line 1: spaces: command not found
Error:  error during XML conversion of with spaces: Command 'COVERAGE_FILE=with spaces coverage xml -o with spaces.xml' returned non-zero exit status 127.
```

The two places with this problem are:

https://github.com/linux-test-project/lcov/blob/34f05f5b1ebd046b5431a0593b2ce58db5b0a275/bin/py2lcov#L179-L182

and

https://github.com/linux-test-project/lcov/blob/34f05f5b1ebd046b5431a0593b2ce58db5b0a275/bin/xml2lcovutil.py#L124-L131

Both cases can and should avoid `shell=True` and be good.

**Comment by hartwork** [comment]
@henry2cox pull request #355 did not solve the underlying problem. I was intentionally not saying that we're dealing with command injection here but maybe I should said that from the beginning. Short article https://security.openstack.org/guidelines/dg_use-subprocess-securely.html#correct is our case. Would you like me to try a pull request myself and for you to be in the review seat this time?

**Comment by hartwork** [comment]
@henry2cox PS: For proof that the problem persists in similar form:

```console
# ./bin/py2lcov "with' 'quotes"
/bin/sh: line 1: quotes: command not found
Error:  error during XML conversion of with' 'quotes: Command 'COVERAGE_FILE='with' 'quotes' 'coverage' xml -o 'with' 'quotes.xml'' returned non-zero exit status 127.
```

**Comment by henry2cox** [comment]
I am of the opinion that a user who deliberately puts quotes and other shell-active characters in paths, is pretty much asking to lose.
I don't worry much about them.

But sure - if you have a portable fix in mind, feel free.

BTW: what timezone are you in?
Do you never sleep?

**Comment by hartwork** [comment]
> I am of the opinion that a user who deliberately puts quotes and other shell-active characters in paths, is pretty much asking to lose. I don't worry much about them.
> 
> But sure - if you have a portable fix in mind, feel free.

@henry2cox thanks! I'll give it a shot.


> BTW: what timezone are you in? Do you never sleep?

:smile: I'm in UTC+1 and I do sleep but not yet :smile: What's your timezone?

**Comment by henry2cox** [comment]
UTC-5, currently.

I think the other aspect is that I'm mostly thinking about (internal) users and various jenkins jobs - which run with the permissions of the user in question, so no particular security issues that didn't already exist.  But yeah - I am permitting you to do something nefarious, if you really want to.

**Comment by hartwork** [comment]
@henry2cox let me first try the pull request and than try answer to that. Starting now…

**Comment by hartwork** [comment]
@henry2cox ready to review now: #356

**Comment by hartwork** [comment]
> so no particular security issues that didn't already exist

@henry2cox I guess it would need an environment where (1) the user can influence the filename and (2) cannot normally execute commands on the local box. I'm imagining some web application that uses LCOV in the backend to offer code coverage services to developers. Signalling this as a vulnerability with a CVE would increase the chance to wake up those parties that indeed operate services like that (if any). In case you do support that view, I can take over the https://cveform.mitre.org/ filing to obtain a CVE with question `Has vendor confirmed or acknowledged the vulnerability?` answered as `yes`.

CC @hannob

**Comment by henry2cox** [comment]
The other remaining issue is that the various callbacks are allowed to be either a module or a script.
If a module:   the callback is invoked as a list - so no interpretation of names or keys:  safe enough, I think - but you do need to verify your callback.
If a script:  then the callback is invoked as a string - because there is no way to know what might be passed.  In this case: yeah.  Carefully crafted name or key could cause trouble.

The workaround would be for the service provider to use only module-based callbacks.

There may be other issues that I haven't thought of.
