### ISSUE TITLE
lcov 1.12 and LLVM 9.0.0 on Mac OS X 10.12.6

### ISSUE THREAD

**Issue by JerryRyan** [linux-test-project/lcov#36]
Using 

```
$ gcov --version
Apple LLVM version 9.0.0 (clang-900.0.38)
  Optimized build.
  Default target: x86_64-apple-darwin16.7.0
  Host CPU: sandybridge
```

geninfo seems to parse this output in a way that causes lcov to think this the equivalent of an older version of gcov... so it goes looking for .da files

If this is a known problem and someone's working it, cool, but if someone needs it worked I'm happy to try to fix it and contribute a patch.

**Comment by oberpar** [comment]
This should be fixed with commit d7cc7591b3a7cc1ec95371d04e4fc46f10b3fd54 which was first included in LCOV v1.13.

**Comment by JerryRyan** [comment]
Is there a easy way to find out when lcov v.1.13 will be released on Macports? thanks!

**Comment by oberpar** [comment]
Unfortunately I don't have any information on Macports.

**Comment by JerryRyan** [comment]
I took the liberty of filing an "update" ticket on macports, asking them to add 1.13 to their distribution.

**Comment by oberpar** [comment]
Closing since the original issue seems to be fixed.
