### ISSUE TITLE
lcov: genhtml (lcov 1.11) fails on virtual destructors

### ISSUE THREAD

**Issue by LukeCz** [linux-test-project/lcov#4]
Hi,

There is an issue introduced in lcov 1.11 that fails on some virtual destructors. Attached below:
1. sample code
2. output from 1.11 (error)
3. output form 1.10 (no error)
I tested this with GCC 4.1.2, Red Hat Linux 5.

[369]/tmp>cat foo.cc

typedef int time_point_t;

class IClock
{
public:
   virtual              ~IClock () { }
   virtual time_point_t Now     () = 0;
};

namespace
{

class DefaultClock : public IClock
{
public:
   virtual time_point_t Now() // override
   {
      return 0;
   }
} defaultClock;
}

int main()
{
return 0;
}

[370]/tmp>g++ -v
gcc version 4.1.2 20080704 (Red Hat 4.1.2-50)

[371]/tmp>g++ foo.cc -fprofile-arcs -ftest-coverage
[372]/tmp>a.out
[373]/tmp>lcov --capture --directory . --output foo.info
Capturing coverage data from .
Found gcov version: 4.1.2
Scanning . for .gcda files ...
Found 1 data files in .
Processing foo.gcda
Finished .info-file creation
[374]/tmp>genhtml --legend --demangle-cpp --output-directory html foo.info
Reading data file foo.info
Found 1 entries.
Demangling 10 function names
genhtml: ERROR: Demangled function name (anonymous namespace)::DefaultClock::~DefaultClock() maps to different lines (21 vs 15) in /tmp/foo.cc
[375]/tmp>/opt/lcov-1.10/bin/lcov --capture --directory . --output foo.info
Capturing coverage data from .
Found gcov version: 4.1.2
Scanning . for .gcda files ...
Found 1 data files in .
Processing foo.gcda
Finished .info-file creation

[376]/tmp>/opt/lcov-1.10//bin/genhtml --legend --demangle-cpp --output-directory html foo.info
Reading data file foo.info
Found 1 entries.
No common filename prefix found!
Writing .css and .png files.
Generating output.
Processing file /tmp/foo.cc
Writing directory view page.
Overall coverage rate:
  lines......: 80.0% (8 of 10 lines)
  functions..: 66.7% (8 of 12 functions)
[377]/tmp>

**Comment by oberpar** [comment]
Sorry for not responding earlier to your e-mail. This is not a regression in lcov 1.11. It is the result of more precise processing of function coverage data for functions which are treated separately by GCC but which "demangle" to the same name. In lcov 1.10, data for such functions would just overwrite each other so the behavior was also not correct.

I'm suggesting the following approach: treat each function for which GCC emits separate coverage data  records as a separate function. In lcov function view, add a sequence number to duplicate function names to allow users to to distinguish each entry. This way no merging on demangled function names is necessary. Correctly interpreting the output will require more consideration on part of the user, but in my opinion this is better than providing incorrect function coverage data based on possibly invalid assumptions.

Any thoughts on this approach?

**Comment by LukeCz** [comment]
Hi Peter,

Thanks you for the response and explanation. I understand why you say it's
not a regression.
I think your solution would be ok. My biggest concern is the process
erroring on the first occurrence and not generating any output.

Best regards,
Lukasz

2015-04-22 14:45 GMT+02:00 Peter Oberparleiter <notifications@github.com>:

**Comment by oberpar** [comment]
I implemented the corresponding approach with commit f87d980929a5a06d49d0a6856f6c3314418c27ef. Please try that version out to see if it resolves the issue you are seeing.

**Comment by oberpar** [comment]
Assuming the issue is fixed.

**Comment by LukeCz** [comment]
I just tested 1.12 and it works. Thank you!
