### ISSUE TITLE
Can lcov have an option that forbid it search source code files?

### ISSUE THREAD

**Issue by LightingContour** [linux-test-project/lcov#40]
Hi! First thanks for you maintain lcov, it's really helps a lot!

But here we got a problem. As we have too much files to cover, each time we use lcov run one loop will take 3-5mins. When all put together it takes too much time.
As we only need the percentage, we'v used "--no-source" option in genhtml, but I notices that lcov will search source code each time and there's no option for me to forbid this step. I believe it will help reduce time a lot ,could you help us? 

Or there is some other ways for us to reduce time cost?

Thanks!

**Comment by oberpar** [comment]
Try disabling branch coverage if you don't need the numbers for that (use command line option --rc lcov_branch_coverage=0 during capture) - this should speed up the process somewhat. I would assume that gcov processing .gcda files takes most time, so disabling source access in lcov would not help. You could also try to collect data for different sub-directories in parallel and later combine the resulting data files.

**Comment by LightingContour** [comment]
Thanks for reply! : )
But I'v tried this option and it shows little help, time spent doesn't change much.

Actually here I'm facing a problem, my team try to use lcov to keep a record of a million-level code program. Each time before we release a new version, we want to make a coverage version for test. This version will be tested by many people and  generate dozens of coverage sets. Each sets have thousands of .gcda files.

I try to figure out how to use a short time to make .info files from dozens of .gcda sets. For now, this progress takes too much, about 4 or more hours. But the window for final test is always short.

Also we'v tried parallel processing, but it doesn't help either.

**Comment by LightingContour** [comment]
We'll try to find some other ways to reduce time. Thanks.
