### ISSUE TITLE
lcov fails to parse gcov-8 output when templates are used

### ISSUE THREAD

**Issue by azeey** [linux-test-project/lcov#41]
The output of gcov-8 includes repeated lines for template instantiations. This could be problematic for `process_dafile` in `geninfo` where `$line_number` is incremented for every line. https://github.com/linux-test-project/lcov/blob/94eac0ee870e58630d8052dca1181b0cf802525f/bin/geninfo#L1388-L1394
The following two examples are based on [gcov's documentation](https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Invoking-Gcov.html#Invoking-Gcov). They show the discrepancy between coverage reports by gcov and lcov. 
 
## Case 1
```C++
template <typename T>
class Foo {
 public:
  Foo() {
  }
};

template class Foo<unsigned int>;

int main() {
  Foo<int> counter;
  return 0;
}
```
### Line Coverage Results:
gcov: 100%
lcov: 77.8%
## Case 2
```C++
template <typename T>
class Foo {
 public:
  Foo() {
  }
};

int NotCovered() {
  int a = 0;
  return a;
}

int main() {
  Foo<int> counter;
  Foo<unsigned int> counter2;
  return 0;
}
```
### Line Coverage Results:
gcov: 66.67%
lcov: 76.9%

**Comment by oberpar** [comment]
Thank your for the report. This should be fixed with commit 1e0df571198229b4701100ce5f596cf1658ede4b. Please re-open if the issue persists.
