### ISSUE TITLE
Support GCOV intermediate format

### ISSUE THREAD

**Issue by marxin** [linux-test-project/lcov#43]
This is follow up of #38.
For GCC 9.1 I'm planning to come up with JSON format of the intermediate representation.
Feel free to comment my patch request:
https://gcc.gnu.org/ml/gcc-patches/2018-09/msg01628.html

**Comment by marxin** [comment]
Note that the format change has landed into GCC's trunk and will be part of next release (9.1).

**Comment by oberpar** [comment]
This should be fixed with commits 75fbae1 (for GCC 9) and ebfeb3e179e450c69c3532f98cd5ea1fbf6ccba7 (for GCC <9).

**Comment by MaskRay** [comment]
Please close this feature request as the previous comment suggested.
