### ISSUE TITLE
--add-tracefile fails in Ubuntu 16

### ISSUE THREAD

**Issue by sgermanserrano** [linux-test-project/lcov#48]
Hi, 

I'm generating a code coverage report in Ubuntu 16. The `-a` / `--add-tracefile` flag fails when lcov is installed via:
`sudo apt-get install lcov`
Instead when installing lcov v1.12 from source this problem does not arise.

**Comment by oberpar** [comment]
This appears to be a problem with the version of LCOV as packaged by Canonical. Please open a bug report against Ubuntu to have this addressed. Closing this issue as there appears to be nothing related to the upstream version of LCOV.
