### ISSUE TITLE
Geninfo can't parse block number

### ISSUE THREAD

**Issue by trotux** [linux-test-project/lcov#49]
Since in gcov was added possibility to distinguish exceptional block, blocks can be marked as '%%%%' and '$$$$' both. This makes it impossible to recognize the block number correctly. So, I suggest correcting it by this patch:
`
diff --git a/bin/geninfo b/bin/geninfo
index ef6a818..e4e083f 100755
--- a/bin/geninfo
+++ b/bin/geninfo
@@ -1901,7 +1901,7 @@ sub read_gcov_file($)
                        # Also remove CR from line-end
                        s/\015$//;
 
-                       if (/^\s*(\d+|\$+):\s*(\d+)-block\s+(\d+)\s*$/) {
+                       if (/^\s*(\d+|\$+|\%+):\s*(\d+)-block\s+(\d+)\s*$/) {
                                # Block information - used to group related
                                # branches
                                $last_line = $2;
`

**Comment by oberpar** [comment]
This should be fixed by e6750800fe4cb89eda1ff80b7a5fe70fe87ede36.

Thanks for reporting!
