### ISSUE TITLE
geninfo: ERROR: build/gcc/i386.gcno: could not open file

### ISSUE THREAD

**Issue by Sameeranjoshi** [linux-test-project/lcov#54]
I have built compiler with --enable-coverage which generates the .gcda files in built directory.

After trying to run lcov as 

`path/to/bin/lcov -c -d  path/to/*.gcda/files/ -o info.info`

I am getting error as:

`Capturing coverage data from .
Found gcov version: 6.3.0
Scanning . for .gcda files ...
Found 460 data files in .
Processing i386.gcda
geninfo: ERROR: build/gcc/i386.gcno: could not open file`

I tried using the latest cloned repo at github but problem still persists.

**Comment by oberpar** [comment]
LCOV needs the .gcno files that are generated during build. It appears that these are not present, or may have been moved during build in your environment. My suggestion: check if you can see .gcno files in your build directory. If not, make sure that they are not removed/moved during build.

**Comment by Sameeranjoshi** [comment]
Thanks,I found that the .gcno files were removed after build, so I tried building another sources. 
Now I currently have 2 sources built 
1. One with .gcno files but not the .gcda files

2. No .gcno files but .gcda files which where generated from many days of testing the compiler,which I won't find feasible to invest again many days of fuzzing by removing them.

If I try copying *.gcno files to the *.gcda file's built directory, I found the coverage but with some warnings as


`build/gcc/tree-ssa-dce.gcda:unknown function '1825969643' `
`build/gcc/tree-ssa-dce.gcda:profile mismatch for '_Z41__static_initialization_and_destruction_0ii'`
Was that the correct approach or should I do the way round?

Thanks

**Comment by oberpar** [comment]
From the warning messages you provided I would assume that the source code used to generate the .gcno files is different from the one use to generate the .gcda files. If the resulting data is not sufficiently correct, my suggestion would be to re-generate the .gcno files from the exact same source as used to generate the .gcda files.

**Comment by Sameeranjoshi** [comment]
So do I need to again build the compiler source code and generate .gcda for
the same sources?
Can I somehow regenerate the .gcno without building the source code again?
As I would again loose the data of the .gcda files

**Comment by oberpar** [comment]
Save the .gcda files, and rebuild the compiler to regenerate the .gcno files. Be sure to use the exact same source code version that was used for the build that generated the .gcda files.

**Comment by Sameeranjoshi** [comment]
I tried saving the .gcda files, Now I have built compiler upto 3 times !. 
I am consistently getting the .gcda file as well as .gcno files generated once I build the compiler (The .gcda shouldn't be present,if I built the compiler,right?).

And the error is:
genhtml: ERROR: cannot read /home/path/to/gcc/cfns.gperf

**Comment by oberpar** [comment]
This does not appear to be an actual problem in the LCOV tooling, but a specific use case scenario that is not working as expected. As there's nothing that could be fixed in LCOV to help here, I'm closing this issue.
