### ISSUE TITLE
geninfo: Use of uninitialized value in hash element since 9aa0d14af

### ISSUE THREAD

**Issue by scpeters** [linux-test-project/lcov#55]
We use lcov with gcc-8 in our bitbucket pipelines, and there seems to be a regression in 9aa0d14af4446ef46d80356849a97bc961a91f97 that generates lots of error messages saying `geninfo: Use of uninitialized value in hash element at /usr/local/bin/geninfo line 3001.` followed by a single error message at the end saying `geninfo: Can't use an undefined value as an ARRAY reference at /usr/local/bin/geninfo line 2889.`.

~~~
$ /usr/local/bin/lcov  --no-checksum --directory /home/developer/ws/ignition/src/ign-math/build --capture --output-file coverage.info
Capturing coverage data from /home/developer/ws/ignition/src/ign-math/build
Found gcov version: 8.2.0
Scanning /home/developer/ws/ignition/src/ign-math/build for .gcda files ...
Found 46 data files in /home/developer/ws/ignition/src/ign-math/build
Processing test/CMakeFiles/gtest.dir/gtest/src/gtest-all.cc.gcda
geninfo: Use of uninitialized value in hash element at /usr/local/bin/geninfo line 3001.
geninfo: Use of uninitialized value in hash element at /usr/local/bin/geninfo line 3001.
...
geninfo: Use of uninitialized value in hash element at /usr/local/bin/geninfo line 3001.
geninfo: Use of uninitialized value in hash element at /usr/local/bin/geninfo line 3001.
geninfo: Can't use an undefined value as an ARRAY reference at /usr/local/bin/geninfo line 2889.
~~~

To demonstrate this, I made a branch that explicitly checks out 1e0df571198229b4701100ce5f596cf1658ede4b (the parent of 9aa0d14af4446ef46d80356849a97bc961a91f97), and invokes `lcov` without the `-q` argument. It works properly and uploads coverage to codecov.

* https://bitbucket.org/ignitionrobotics/ign-math/commits/73f0c546d8621c29700dd19b940a86e255bf7649
* working pipeline: https://bitbucket.org/ignitionrobotics/ign-math/addon/pipelines/home#!/results/1152

I then made a follow-up commit that checks out 9aa0d14af4446ef46d80356849a97bc961a91f97, and it fails with the error message I described above:

* https://bitbucket.org/ignitionrobotics/ign-math/commits/73a4c880543f0d7e0224a5aada775127376a2d59
* broken pipeline: https://bitbucket.org/ignitionrobotics/ign-math/addon/pipelines/home#!/results/1153

**Comment by oberpar** [comment]
Thank you for the quick feedback. This is indeed a bug introduced by commit 9aa0d14. I was able to reproduce the problem and isolate its cause. It should be fixed with commit 04335632c371b5066e722298c9f8c6f11b210201.

**Comment by scpeters** [comment]
Thanks, I'm testing here:

* https://bitbucket.org/ignitionrobotics/ign-math/commits/6f77606fbdf4866630c1022e29afefa6bc46f9b0

**Comment by scpeters** [comment]
Yes, it looks to be fixed, thank you!
