### ISSUE TITLE
genhtml result codeview  show up unreadable code 

### ISSUE THREAD

**Issue by zhaojianping** [linux-test-project/lcov#6]
genhtml default output charset is UTF-8 
codeview  show up unreadable code if exists no ascii charactor in souce code and encoding is GBK
how modfiy default charset ?
![image](https://cloud.githubusercontent.com/assets/5487826/8178130/21a08bce-143e-11e5-8558-2f0d24cd66cd.png)

**Comment by oberpar** [comment]
See man lcovrc.5:
[...]
       genhtml_charset = charset

              Specify the character set of all generated HTML pages.

              Use this option if the source code contains characters which are
              not  part of the default character set. Note that this option is
              ignored when a custom HTML prolog is specified  (see  also  gen-
              html_html_prolog).

              Default is UTF-8.

**Comment by zhaojianping** [comment]
thank you
