### ISSUE TITLE
Add anchors for every line in HTML version of source code

### ISSUE THREAD

**Issue by pwithnall** [linux-test-project/lcov#61]
When generating the HTML output, there’s currently only an anchor at the start of every function. It would be more useful if there was one per line of output, so that (for example) one can link to a specific line which needs looking at from a bug report.

**Comment by oberpar** [comment]
This functionality has been introduced with commit abd8bed2b013334d4ef978abadbfff6cc6f3d55d. Is there anything else missing?

**Comment by pwithnall** [comment]
Oh, nice! Sorry, I didn’t check `master`; only version 1.13 which is what my system has. Let’s close this, and I’ll open a new issue if there’s a problem with the functionality when it eventually gets packaged in Fedora. Thanks a lot.
