### ISSUE TITLE
How to cover virtual method present in the base class using LCOV 

### ISSUE THREAD

**Issue by prem1995** [linux-test-project/lcov#69]
Hi All,

I'm trying to understand why this virtual method in an abstract class is not covered if there are hundreds of calls to it from derived classes.
For the below example C++ code I want to know a way to cover the virtual method in Parent class to achieve 100%function coverage. please let me know if any to cover the method1() function in the Parent class.

I've prepared an equivalent example: an abstract class with a virtual method which is called by the child class. Here it is:

#include <iostream>

class Parent {
public:
  virtual ~Parent() {
    std::cout << "I am parent's destructor" << std::endl;
  }
  virtual void method1() {
    std::cout << "I am parent's method 1" << std::endl;
  }
  virtual void method2() = 0;
};

class Child : public Parent {
public:
  ~Child() {
    std::cout << "I am child's destructor" << std::endl;
  }
  void method1() {
    Parent::method1();
    std::cout << "I am child's method 1" << std::endl;
  }
  void method2() {
    std::cout << "I am child's method 2" << std::endl;
  }
};

int main(int argc, char** argv) {
  Parent* obj = new Child();
  obj->method1();
  obj->method2();
  delete obj;
  return 0;
}

**Comment by latk** [comment]
Are you compiling with optimizations? If so, the compiler will likely inline the `Parent::method1()` call. The inlining should preserve correct coverage metadata, but the coverage data only reflects the structure of the underlying assembly code, not the structure of the source code. After inlining, there is no *call* to Parent's `method1()`, even though the *contents* of that method are executed.

You have the following options available:

* Compile without optimizations (`-O0`)

* Don't make Parent's `method1()` inline. Methods that are defined within a class/struct are implicitly inline. Here, just define it outside of the class:

    ``` c++
    class Parent {
      ...
      virtual void method1();
      ...
    };

    void Parent::method1() {
      ...
    }
    ```

* Write a test case that invokes Parent's `method1()` through a virtual call, for example by creating a new subclass:

    ``` cpp
    struct JustForTesting: Parent {
      void method2() override {}
    };

    __attribute__((noinline))  // ensure that a virtual call is used despite optimizations
    void virtual_call_to_method1(Parent& target) {
      target.method1();
    }

    ...
    JustForTesting object;
    virtual_call_to_method1(object);
    ```

**Comment by prem1995** [comment]
Sorry my bad I asked wrong question, Actually what I wanted to ask is that is there a way to cover the method1() of Parent class without calling from Child method1() implementation like from main function. It is also ok to suppress the count of the virtual base class implementation by giving an option if any in LCOV tool.

Here is the modified code. In this how can I cover the method1() implementation of Parent class
#include

class Parent {
public:
virtual ~Parent() {
std::cout << "I am parent's destructor" << std::endl;
}
virtual void method1() {
std::cout << "I am parent's method 1" << std::endl;
}
virtual void method2() = 0;
};

class Child : public Parent {
public:
~Child() {
std::cout << "I am child's destructor" << std::endl;
}
void method1() {
std::cout << "I am child's method 1" << std::endl;
}
void method2() {
std::cout << "I am child's method 2" << std::endl;
}
};

int main(int argc, char** argv) {
Parent* obj = new Child();
obj->method1();
obj->method2();
delete obj;
return 0;
}

**Comment by latk** [comment]
To cover the parent method, you will need to create a test that invokes the parent method – I've included such an example at the end of my previous comment.

The Gcov coverage data counts with function bodies were executed, not through which name the function was called. Lcov is therefore correct to mark `Parent::method1()` as uncovered as that function body was never executed. It's not possible to change this unless lcov becomes far far more complicated than it already is.

**Comment by henry2cox** [comment]
No updates for several years - and original question seems to have been user misunderstanding.

In any case:  I believe this issue is resolved - so closing now.
If you think that there is still a problem:  please reopen this issue or file a new one.  Please include a detailed description of the problem and a testcase which illustrates the issue.

I am attempting to clean up the issue list to make it easier to see what actual problems still exist
Henry
