### ISSUE TITLE
Combining tracefiles

### ISSUE THREAD

**Issue by juraj67** [linux-test-project/lcov#70]
Hi,
I'm trying to combine 2 .info files which contain information about same source directory using **-a** option.
**First .info file** is initial file(lcov --capture -i command on my source dir) and **second .info file** is from tests(from testing my source directory). 

After combining these files, lines and functions are OK, but branches(from simple IF statement) are not joined but divided. It results to wrong branch coverage -> 25% instead 50%.

**This is my initial .info file from source dir** - branch coverage is 0%
![null](https://user-images.githubusercontent.com/47740276/65219759-85329380-dab9-11e9-8419-ea94985c373e.PNG)

**This is my .info file from testing source dir** - branch coverage is 50%
![test](https://user-images.githubusercontent.com/47740276/65218764-721ec400-dab7-11e9-91fa-25dcad2d7a59.PNG)

**Combined test+initial .info file**  - branch coverage is wrong - 25%
![combined](https://user-images.githubusercontent.com/47740276/65218754-6f23d380-dab7-11e9-8601-9252d6bb4109.PNG)

I think it's caused by not equal branch numbers in .info file on BRDA line(third number), so lcov doesn't combine it properly.

For example(this is combined .info file):
![brda](https://user-images.githubusercontent.com/47740276/65228237-6983b900-daca-11e9-8950-f4b58a6fe322.PNG)

I would like to ask, if there is a way to do it correctly.
Thanks in advance for your help.

**Comment by oberpar** [comment]
I wonder where these different branch numbers come from. Could you provide a minimized source example where this problem occurs?
