### ISSUE TITLE
Feature Request - Supporting differential coverage

### ISSUE THREAD

**Issue by shameerkc** [linux-test-project/lcov#71]
Hi,

We have a running project with quite a large code-base. For new Sprints, we keep adding new code/modify/delete. The complete code coverage report does not bring much value to the project, since many of the times, we end up having very less coverage for the base code. Also, it is not clear if the new changes are covered or not.

The request is to support providing a differential coverage report - the base source code folder can be considered as an input (--old <dir) and latest code based as another input.

We checked further to see if we have any such tool already in place.

Thank you so much in advance for the help.

**Comment by henry2cox** [comment]
I implemented differential coverage as well as date- and owner binning.
See https://github.com/henry2cox/lcov branch 'diffcov_initial'

the example in .../tests/gendiffcov/simple illustrate most of the features.

This is tested with perl 5.12.5 and gcc/8.3.0 and 9.2.0. 
The 'gendiffcov' script is a superset of 'genhtml', and is where I implemented the differential features.

Henry

**Comment by henry2cox** [comment]
FWIW:  that branch has a few more fixes and some more features now.
the best place to start is probably to cd to the 'tests/gendiffcov/simple' directory, and run 'sh script.sh'.  It will generate a number of  HTML result directories, to show the effect of various options and option combinations.

**Comment by henry2cox** [comment]
A paper describing the concepts and approach implemented in the lcov version referenced above can be found at https://arxiv.org/abs/2008.07947.

**Comment by henry2cox** [comment]
Just pushed support for differential categorization of function coverage metrics.
(Now line, branch, and function metrics are all supported.)

**Comment by henry2cox** [comment]
No updates to this issue from anyone but me since it was opened.
I believe that it is fixed/resolved - so closing now.

If you still see problems or this issue is not resolved to your satisfaction, please reopen this issue or file a new one.
Please give a detailed description of the problem, and if possible include a testcase (in this case:  probably a set of screenshot mockups to show what you want to see).

Henry
