### ISSUE TITLE
Duplicate FN statement for the same method

### ISSUE THREAD

**Issue by NedK123** [linux-test-project/lcov#77]
I'm parsing the total.info file which is the result of running a few lcov commands on my source code in order to build a service that provides coverage information when needed. 
lcov also provides a nice html ui to browse code coverage.
The problem is that i'm getting different values in terms of function coverage in my service than the html ui of lcov.

I'm calculating code coverage on end to end tests and not on unit tests.

Gcc version is 4.8.5 Red Hat

Lcov version is 1.14

The launched lcov commands are in the following order:

1- `time lcov -c -i -d . --rc geninfo_adjust_src_path="{path} => " -o base.info `

2- `time lcov -c -d . --rc geninfo_adjust_src_path="{path} => " -o test.info`

3- `time lcov -rc geninfo_adjust_src_path="{path} => " -a base.info -a test.info -o total.info `

To make it simpler here are 2 sections from the total.info file.

In this section, the parsing is working correctly
There are 5 functions

```
TN:
SF:{path}/FileOne.hpp
FN:22,_methodName
FN:29,_methodName
FN:31,_methodName
FN:40,_methodName
FN:48,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:6,_methodName
FNDA:6,_methodName
FNDA:0,_methodName
FNF:5
FNH:2
DA:22,6
DA:29,12
DA:31,6
DA:33,24
DA:34,0
DA:35,6
DA:36,6
DA:40,0
DA:42,0
DA:43,0
DA:45,0
DA:48,0
DA:50,0
DA:51,0
DA:54,0
LF:15
LH:6
end_of_record
```

The parsing problems are happening in the section below as some functions appear to have duplicate FN statement (They all start at the same line, so I assume this is referring to the same function)

```
TN:
SF:{path}/FileTwo.hpp
FN:32,_methodName
FN:39,_methodName
FN:48,_methodName
FN:58,_methodName
FN:64,_methodName
FN:100,_methodName
FN:116,_methodName
FN:116,_methodName
FN:128,_methodName
FN:128,_methodName
FN:128,_methodName
FN:128,_methodName
FN:132,_methodName
FN:138,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNDA:0,_methodName
FNF:14
FNH:0
DA:32,0
DA:33,0
DA:39,0
DA:40,0
DA:41,0
DA:44,0
DA:48,0
DA:49,0
DA:51,0
DA:52,0
DA:55,0
DA:56,0
DA:58,0
DA:59,0
DA:60,0
DA:61,0
DA:62,0
DA:64,0
DA:65,0
DA:66,0
DA:68,0
DA:91,0
DA:92,0
DA:96,0
DA:97,0
DA:100,0
DA:101,0
DA:102,0
DA:104,0
DA:105,0
DA:106,0
DA:112,0
DA:116,0
DA:117,0
DA:118,0
DA:121,0
DA:122,0
DA:125,0
DA:128,0
DA:129,0
DA:130,0
DA:132,0
DA:133,0
DA:134,0
DA:135,0
DA:138,0
DA:139,0
DA:140,0
DA:141,0
DA:142,0
DA:145,0
LF:51
LH:0
end_of_record
```

At lines 116 & 128, the functions are as follows:

```
     115             :    template <typename UnaryOp>
     116           0 :    void remove_if(UnaryOp op) {
     117           0 :       for (typename Items::iterator it = m_items.begin(), end = m_items.end(); it != end;) {
     118           0 :          if (!op(*it))
     119             :             ++it;
     120             :          else {
     121           0 :             shutItem(*it);
     122           0 :             m_items.erase(it++);
     123             :          }
     124             :       }
     125           0 :    }

     127             :    template <typename Op>
     128           0 :    void for_each(Op &op) {
     129           0 :       std::for_each(m_items.begin(), m_items.end(), op);
     130           0 :    }
```

My question is why are some functions appearing multiple times (who's "FN:{}" start at the same line)?

**Comment by NedK123** [comment]
Hello @oberpar 
I've seen you fixed a similar issue but for gcc 8 in [1e0df57](https://github.com/linux-test-project/lcov/commit/1e0df571198229b4701100ce5f596cf1658ede4b).

I'm using the latest version of lcov but still facing the problem.

can you please advise?

regards

**Comment by henry2cox** [comment]
I see the same issue in the 'geninfo' output from lcov release 1.15, especially for branch coverage metrics.
In some cases - but not all cases - the number of branch elements is different between the groups (one group will have 2, then the next appearance may have 4, etc)

In the info file for 'stl_tree.h', in a gcc/9.2.0-compiled project:
DA:277,12
DA:277,64030
DA:278,27955
DA:278,12
DA:278,64030
DA:285,0
DA:285,0
DA:285,12090
DA:287,0
DA:287,0
DA:287,12090
...
and some funny branch coverage (note that the lines and branches are interleaved in this output example)
DA:2095,0
BRDA:2095,0,0,-
BRDA:2095,0,1,-
DA:2095,0
BRDA:2095,0,0,-
BRDA:2095,0,1,-
DA:2095,3
BRDA:2095,0,0,3
BRDA:2095,0,1,0
DA:2096,0
BRDA:2096,0,0,-
BRDA:2096,0,1,-
DA:2096,0
BRDA:2096,0,0,-
BRDA:2096,0,1,-
DA:2096,3
BRDA:2096,0,0,3
BRDA:2096,0,1,0
DA:2098,21150
DA:2098,1061
DA:2098,3

These examples are far from unique, and are not cherry-picked.  There are many, many files with the same issues, and many, many line in each file.

Henry

**Comment by henry2cox** [comment]
FWIW:  the '--filter function' feature that I added hacks around this issue (by merging coverage elements for functions which have the same file/line location.  See pull request #86.
One application I'm using this for is basically a rather large template metaprogram - so there are very many template instances and many methods which are not used/never intended to be used.  Filtering seems to make the result actionable.   (Hard to know where to start, with more than 300K unused function...almost all of which are don't care.)

**Comment by henry2cox** [comment]
This issue may now be fixed in current TOT.
The various filters mentioned above are merged, and the code which was generating duplicate line, branch, and function entries has been refactored and should not longer occur.
Note that you may see multiple function entries on the same line in cases of multiple parameterizations of C++ templates.  They can also occur if the compiler generates multiple versions of inline functions which were instantiated out-of-line.

In any case:  in view of the age of this issue and that I think that it is fixed, I will close this issue.
If you think that problems remain, please reopen this issue or file a new one.
Thanks
Henry
