### ISSUE TITLE
Publish release tarballs on github.com

### ISSUE THREAD

**Issue by sofar** [linux-test-project/lcov#8]
Please consider publishing your release tarballs on github (in addition or in replacement of SF.net). It's as simple as:

- click on "XXX releases" from the project page
- click on a tag ... "v1.11"
- click the "Edit tag" button on the top right
- Use the "Attach binaries by dropping them here or ￼ selecting them." area

You can insert any tarball here, including the `make dist` product release.

Thanks!

**Comment by oberpar** [comment]
Fixed, thanks for pointing this out.

**Comment by sofar** [comment]
Awesome!!
