### ISSUE TITLE
geninfo --include/--exclude options only work on some cases

### ISSUE THREAD

**Issue by petere** [linux-test-project/lcov#84]
The `geninfo` options `--include` and `--exclude` are only looked at by `process_dafile` but not by `process_intermediate` or `process_initial`.  When using a workflow using the `lcov --initial` option, it is therefore impossible to effectively exclude files from consideration. I don't know what the meaning of the "intermediate" mode is, but it appears that it is chosen in my case. So the effect is that `--include` and `--exclude` are basically completely ignored.

**Comment by oberpar** [comment]
`process_intermediate` applies filtering based on `--include` and `--exclude` options via sub-function `filter_source_files`. I also just checked that it works, both with actual data and initial data. "intermediate" refers to a new output format supported by `gcov` for GCC versions 8 and above.

Could you provide the compiler version you are using and an example invocation of `lcov`/`geninfo` that is not working as expected?

**Comment by marc-groundctl** [comment]
I can reproduce this as well on a Mac when not using the intermediate format.  The issue appepars to be that `process_graphfile`, when looping over the files, [only checks if the files are external, not excluded](https://github.com/linux-test-project/lcov/blob/d100e6cdd4c67cbe5322fa26b2ee8aa34ea7ebcf/bin/geninfo#L3186).  Here is an example:

```
$ cat x.c
int main()
{
	return 0;
}
$ clang x.c -o x --coverage
$ lcov --capture --initial --directory . --exclude "*"
Capturing coverage data from .
Found LLVM gcov version 11.0.0, which emulates gcov version 4.2.0
Scanning . for .gcno files ...
Found 1 graph files in .
Processing x.gcno
TN:
SF:/tmp/x.c
FN:1,main
FNDA:0,main
FNF:1
FNH:0
DA:1,0
DA:3,0
LF:2
LH:0
end_of_record
Finished .info-file creation
$ lcov --version
lcov: LCOV version 1.15
$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ gcov --help
OVERVIEW: LLVM code coverage tool

USAGE: gcov [options] SOURCEFILE

OPTIONS:

Color Options:

  -color         - Use colors in output (default=autodetect)

General options:

  -a             - Display all basic blocks
  -b             - Display branch probabilities
  -c             - Display branch counts instead of percentages (requires -b)
  -f             - Show coverage for each function
  -l             - Prefix filenames with the main file
  -n             - Do not output any .gcov files
  -o=<DIR|FILE>  - Find objects in DIR or based on FILE's path
  -p             - Preserve path components
  -u             - Display unconditional branch info (requires -b)

Generic Options:

  -help          - Display available options (-help-hidden for more)
  -help-list     - Display list of available options (-help-list-hidden for more)
  -version       - Display the version of this program

Internal and debugging options:

  -dump          - Dump the gcov file to stderr
  -gcda=<string> - Override inferred gcda file
  -gcno=<string> - Override inferred gcno file
```

**Comment by henry2cox** [comment]
Can you try this again with current TOT?
I think that it is fixed.
Thanks
Henry

**Comment by henry2cox** [comment]
No update from anyone but me in a very long time.
I believe the problem has been addressed - so closing this issue now.

If there is still a problem, please reopen this issue or file a new one.  Please include a detailed description of the problem and include small testcase if possible.
I am trying to clean up the list of open issues to make it easier to find problems that still need to be addressed.
Henry
