### ISSUE TITLE
1.5 version does not work well with mingw gcc 5.1

### ISSUE THREAD

**Issue by xiaoyun94** [linux-test-project/lcov#91]
i describe the question before, but the solution is not what i expect!
lcov use gcov to collect info, but gcov at mingw-gcc-5 output line with ending \r\n not \n
https://github.com/linux-test-project/lcov/issues/88

**Comment by xiaoyun94** [comment]
chomp does not remove \r

**Comment by xiaoyun94** [comment]
https://github.com/linux-test-project/lcov/pull/92

**Comment by xiaoyun94** [comment]
#92

**Comment by GitMensch** [comment]
The PR was "kind of included" and the fix is now available with lcov 1.16 - so I think this issue should be closed as solved.
