### ISSUE TITLE
Update Needed for Download Page

### ISSUE THREAD

**Issue by scintiller** [linux-test-project/lcov#93]
In the `2. Installing LCOV` part of [README.md](https://github.com/linux-test-project/lcov), it guided user to go to  [Download Page](http://ltp.sourceforge.net/coverage/lcov.php). But the `lcov 1.14` here is out-dated. To be more specifically, it isn't compatible with `gcc 9.3`. I saw the discussion over [this thread](https://github.com/Homebrew/homebrew-core/issues/50043), and believe someone has fixed it but hasn't update the new package in the [Download Page](http://ltp.sourceforge.net/coverage/lcov.php). 
I also tried use `apt install lcov` to install it in Ubuntu and it works. In this way the `lcov` is compatible with `gcc 9.3`.
Therefore, can someone update the [Download Page](http://ltp.sourceforge.net/coverage/lcov.php)? It's a little bit misleading.

**Comment by GitMensch** [comment]
The links were changed with 6da8399c7a7a3370de2c69b16b092e945442ffcd, so I think this part is now fully covered. For the website adjustment _in general_, see #151.

**Comment by henry2cox** [comment]
No responses/no updates in a very long time. I believe that this issue has been addressed.

If there is still a problem, please either reopen this issue or file a new one.
Please include a detailed description of the problem, and ideally include a testcase which exhibits the issue.
Henry
