### ISSUE TITLE
Strange 'function coverage' result in C++ code?

### ISSUE THREAD

**Issue by henry2cox** [linux-test-project/lcov#98]
I see some strange results that I do not understand.
For example, I have a singleton class "ErrorManager" whose constructor and destructor are defined in file 'errorManger.cpp'
The "function" coverage page for the file contains the following (extracted - many other lines elided):
![image](https://user-images.githubusercontent.com/68852529/95350714-78343e00-088e-11eb-86a8-2c1c8c07abad.png)
(note the ErrorManager::~ErrorManager() is hit zero times).

Slightly later on the page, I find:
![image](https://user-images.githubusercontent.com/68852529/95350976-b7fb2580-088e-11eb-8e34-e3b4c5d9fa9f.png)
Note that now we see that "ErrorManager::ErrorManager().2" is hit 2415 times.
(It would be a good guess, to suspect that this regression suite contains 2415 testcases.)

The hrefs for both links point to the same line (.../errorManager.cpp:147) - so it seems clear that these two are aliases for the same function.

Question:  why is geninfo (or gcov??) creating these alias entries?  Is there a way to stop it?
This is a problem because we tend to care about uncovered code - but quite a few of the "uncovered" functions that we see in the function coverage report are bogus.

I am considering to add a simple filter, to merge the data for all "unique" functions which are declared on the same file/line.
I suspect that the resulting report will be more useful in our current methodology.

**Comment by henry2cox** [comment]
FWIW:  a trivial filter was so easy that I just did it.
The effect was to cut the number of unique functions reported by more than 90% in the project that I used for testing.
(Most of the merged aliases are different template instantiations.)

**Comment by xaizek** [comment]
> why is geninfo (or gcov??) creating these alias entries?

It's the compiler. There can be different versions of destructors (or functions in general). Some with a call to `delete this`, some without. I think this happens when the class has a virtual table. 

Haven't tried it, but you can try compiling with `-ffunction-sections` and linking with `-Wl,--gc-sections`. If those functions are unused, the linker should drop them. In general your filter will produce better results though, because some versions of the same function might be used only partially.

**Comment by henry2cox** [comment]
Hi –

Thanks for the quick response and the explanation.
As it turns out, our makefiles already specify ‘-ffunction-sections’ and --gc-sections – so we see the issues with those flags.  (I don’t know what we would see if we didn’t use the flags – and I no longer recall why we thought we needed to add them in the first place.)

Filtering it is, then (for the moment, at least).

It would not be hard to continue to report all the aliases as well (e.g., in an ‘expanded function table’, not unlike the testcase ‘show-details’ table) – but I didn’t implement that because I don’t think any of my users will care.

Maybe an even better approach would be to simply merge everything that _doesn’t_ look like a template instantiation difference – and to keep aliases for everything that does.
(Again:  not done.)

Henry

**Comment by henry2cox** [comment]
Replying to my own issue....
FWIW:  I implemented the 'function/alias' table described above (keeping all the aliases).  The function coverage detail page now shows each alias groups (in sorted order, always keeping the groups together).

**Comment by henry2cox** [comment]
#169 is merged - so I'm closing my issue :-)
The workaround is not perfect - but it it good enough.
